openfoodfoundation/ofn-install

README.md, roles/app/tasks/main.yml, roles/app/templates/application.yml.j2, roles/deploy/tasks/main.yml, vars.example.yml
Updates to match https://github.com/openfoodfoundation/openfoodnetwork/issues/443 and also resolves the issue that caused #21.
=> Remove spree.rb

inventory/group_vars/de.yml, inventory/hosts
Is this localized as intended?
=> german locale vars/group 

inventory/group_vars/all.yml, playbooks/restore_backup.yml, roles/app/tasks/main.yml
I've added this as a way to trigger a new install being synced directly from an existing backup.
Also @mkllnk do you think https://github.com/openfoodfoundation/openfoodnetwork/blob/master/config/initializers/0_depricated_db2fog.rb should be deleted?
=> Be able to restore the database using db2fog from last backup

bin/requirements.yml, playbooks/provision.yml, roles/cert/tasks/main.yml, roles/common/tasks/main.yml, roles/webserver/tasks/main.yml, roles/webserver/templates/unicorn.service.j2
Changes to support building on Ubuntu 16.04.
=> Ubuntu 16.04 test

roles/app/templates/application.yml.j2
Some new config variables to be setup in application.yml.
=> add config vars

roles/app/templates/post-receive.j2
This is related to Task https://github.com/openfoodfoundation/openfoodnetwork/issues/1562 
for PR https://github.com/openfoodfoundation/openfoodnetwork/pull/1564 because of https://github.com/fnando/i18n-js/issues/306
=> Running tmp:cache:clear for i18n-js before assets:precompile

.travis.yml, inventory/dev, inventory/host_vars/local.ofn.org/config.yml, playbooks/development.yml, roles/dbserver/tasks/main.yml, roles/default_user/tasks/main.yml, scripts/config/ansible.cfg, scripts/config/lxc.cfg, scripts/create-container.sh, scripts/db-setup.sh, scripts/provisioning-dev.sh
I propose this development playbook and this automation scripts to help create a development environment using [LXC](https://linuxcontainers.org/) in your local Linux machine.
This proposal is **only for the development environment**, it doesn't affect how we provision production and staging machines. 
The idea is to use `default_user.yml` playbook to create an admin user and use `development.yml` playbook to provision the container with the tools needed to run the application.
We create the following Quick Start guide to help new user to install the development environment and to make it easy for the new contributors.
This document will guide you through creating an LXC container which you start/stop to develop ofn,
provision it with everything you need to develop ofn and provide you …
=> Use LXC for development environment

roles/webserver/templates/unicorn.service.j2
In this way every process started from unicorn will have the correct Rails environment.
=> Use rails_env variable to populate RAILS_ENV env var in unicorn.service.j2

roles/unicorn_user/tasks/main.yml, roles/unicorn_user/templates/bash_profile.j2, roles/unicorn_user/templates/defaults.j2
Solve https://github.com/openfoodfoundation/ofn-install/issues/85
We need this especially for `RAILS_ENV`
=> Add default environment variables for unicorn user

roles/app/tasks/main.yml
Fixes issue reported here https://github.com/openfoodfoundation/ofn-install/pull/87#issuecomment-340255922
=> Fix bugsnag configuration

inventory/group_vars/all.yml
Addressing #107.
Removing this header so it can be altered programmatically from within Rails. Needed for embedded shopfronts functionality.
=> Don't set X-Frame-Options in nginx

inventory/group_vars/_example.yml, inventory/group_vars/es.yml, roles/app/templates/application.yml.j2
Added the AVAILABLE_LOCALES env var in the application.yml template so it can be defined in every instance. I also set the available_locales to "es,ca,pt" in Katuma (es.yml).
=> Added AVAILABLE_LOCALES env var in ofn-install

inventory/group_vars/all.yml
Closes #111 . This a more useful default than an old tag
=> Set master as the default branch to deploy

inventory/host_vars/_example.com/config.yml, inventory/host_vars/_example.com/secrets.example.yml, inventory/host_vars/alpha.katuma.org/config.yml, inventory/host_vars/staging.katuma.org/config.yml, roles/unicorn_user/templates/defaults.j2
these ENV vars provide the data required for https://github.com/openfoodfoundation/openfoodnetwork/pull/2148 to work and need to be specified per instance and environment.
**MAKE SURE YOU SPECIFY AND PROVISION THEM IF YOU MANAGE AN OFN INSTANCE**
=> Add mail settings' env vars to unicorn_user

roles/deploy/handlers/main.yml
Fixes #82 
Another approach than #143 , this one IMO much simpler and works fully including restarting nginx
I tested it together with #124 and `site.yaml` run fully without any fails resulting in functioning site (minus delayed jobs running)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openfoodfoundation/ofn-install/144)
=> manage services as root

inventory/hosts
We upgraded to a bigger machine.
=> Update Katuma's staging IP

inventory/group_vars/fr.yml
=> Add sysadmins to FR

inventory/group_vars/_example.yml, inventory/group_vars/fr.yml
Setting the default OS language to English for the new French server, and making sure French is installed so it is available.
Also added some notes to the `example.yml` file for reference.
=> FR language packs

inventory/host_vars/prod.openfoodfrance.org/config.yml, inventory/hosts
Adding this as part of the OFFrance migration.
The migration is finished so I have updated the PR and we can merge the changes now.
=> Update offrance fr-prod config

inventory/host_vars/staging.openfoodnetwork.org.uk/config.yml, inventory/host_vars/www.openfoodnetwork.org.uk/config.yml
Increasing timeouts for UK servers due to issue https://github.com/openfoodfoundation/openfoodnetwork/issues/2545.
=> Increase UK timeouts

inventory/group_vars/fr.yml, inventory/host_vars/staging.openfoodfrance.org/config.yml, inventory/hosts
…and granted access to luis to this server.
This is part of fixing fr_staging to work normally with ofn-install.
There are still a few issues on the provisioning but the deploy is working with this change.
=> Added correct domain name (.org not .fr) to the config of fr_staging

inventory/host_vars/staging.openfoodnetwork.org.au/config.yml, inventory/hosts
The old staging2 doesn't exist any more.
=> Add new Australian staging server

inventory/host_vars/staging.openfoodnetwork.org.au/config.yml
It's quite useful for testing if multiple languages are available.
=> Activate language switcher

files/keys/hugo.pub, inventory/group_vars/fr.yml
I need to inspect some behavior in the FR production server
=> Add Hugo to french group & public key

inventory/group_vars/be.yml
=> Use new l10n_be repo

inventory/group_vars/es.yml
This will allow our friends from Piemonte to give OFN a try. I hope they like it decide to join OFN!
=> Enable Italian in Katuma

.travis.yml, inventory/host_vars/_example.com/secrets.example.yml, roles/app/defaults/main.yml, roles/app/tasks/main.yml, roles/deploy/defaults/main.yml, roles/deploy/tasks/main.yml, roles/webserver/tasks/main.yml
Fixes #331. It locks the the ansible-lint version to the current 4.1.0 and updates the code to comply to it.
=> Adapt to ansible-lint 4.1.0

inventory/host_vars/_example.com/secrets.example.yml
Bugsnag has been overlooked by many newcomers. Maybe that was because it was missing in the secrets template?
=> Add bugsnag key template to example secrets

inventory/host_vars/www.openfoodnetwork.org.uk/config.yml
Closes #355
This increases the `unicorn_workers` to 3 on UK production and sets 1GB of swap. Hopefully the catchy title will get it approved and merged quicker. :wink: 
:unicorn: :unicorn: :unicorn:
=> Triple Unicorn Rainbow Explosion

Vagrantfile, bin/requirements.yml, playbooks/provision.yml, roles/common/tasks/main.yml, roles/compatibility/tasks/main.yml
Closes #343 
Closes #344 
This PR bring compatibility for Ubuntu 18 (Bionic Beaver) to ofn-install. I've tested the `setup`, `provision`, and `deploy` playbooks with these changes on both Ubuntu 16 and Ubuntu 18 boxes. Both are running fine, and the fatal errors are fixed for Ubuntu 18.
Additional notes are in the 2 issues above.
Note: this requires an update of the community roles with:
`ansible-galaxy install -r bin/requirements.yml --force`
=> Bionic beaver

roles/webserver/handlers/main.yml, roles/webserver/tasks/main.yml, roles/webserver/templates/unicorn.service.j2
Closes #380 
Reloads unicorn if it's configuration has been changed during provision.
=> Reload unicorn if configs have been updated during provision

roles/semaphore_deployment/tasks/main.yml, roles/semaphore_deployment/templates/deploy.j2
Removing some more code as deployment is no longer coupled to secrets.
=> Deployment update

inventory/host_vars/www.openfoodnetwork.org.uk/config.yml
Delivery of additional unicorns to the UK, as ordered in #356.
=> Increase unicorn_workers to 4 for UK production

.travis.yml, inventory/group_vars/travis.yml, inventory/host_vars/local_travis/config.yml, inventory/hosts, playbooks/deploy.yml, playbooks/provision.yml
Part one of #414 
This introduces a basic CI build, where we do a real run-through of `site.yml`.
Given that it's the 50th anniversary of the moon landings this year, I think I should point out that this is: one small step for `travis.yml`, one giant leap for `ofn-install`...
=> Travis CI build

inventory/group_vars/all.yml
The previous version of this PR #410 didn't get merged properly because the branch wasn't set to `master`.
=> Enable capturing of PostgreSQL's stderr

inventory/group_vars/all.yml, inventory/group_vars/au.yml, inventory/group_vars/be.yml, inventory/group_vars/ca.yml, inventory/group_vars/de.yml, inventory/group_vars/es.yml, inventory/group_vars/fr.yml, inventory/group_vars/norway.yml, inventory/group_vars/uk.yml, inventory/group_vars/us.yml
Adds a "core devs" list in `all.yml` and refactors existing `users_sysadmin` entries to utilize it.
=> Refactor ssh key lists

inventory/host_vars/_example.com/secrets.example.yml
Apart from avoiding confusion, I find it easier to read with separate paragraphs.
=> Fix playbook to run to enable db_integrations

inventory/host_vars/prod2.openfoodnetwork.org.au/config.yml, inventory/hosts
Some update configuration for the Australian production server. The server has been partly provisioned and its current status is documented at https://github.com/openfoodfoundation/ofn-install/wiki/Australia.
There will be more updates while progressing on this task. But since I'm going on holiday for two weeks I didn't want to change too much right now.
=> Australia update

inventory/host_vars/prod2.openfoodnetwork.org.au/config.yml
Adding the Zapier configuration. This needs https://github.com/openfoodfoundation/ofn-secrets/pull/13.
=> Add Zapier access to AU

roles/dbserver/tasks/main.yml
Closes https://github.com/openfoodfoundation/ofn-install/issues/72
=> Explain the use of the .pgpass file

inventory/group_vars/au.yml
https://github.com/openfoodfoundation/ofn-install/issues/438
This depends on https://github.com/openfoodfoundation/openfoodnetwork/pull/3865 to add the locale before it can be used.
=> Use new Australian locale

.devenv, inventory/group_vars/lxc.yml, playbooks/development.yml
This adds the `.devenv` file I'm currently using and explains a bit how this is meant to work with LXC containers.
=> Add a .devenv with some details

inventory/group_vars/za.yml, inventory/host_vars/ofn.kandu.co.za/config.yml, inventory/host_vars/www.openfoodnetwork.org.za/config.yml, inventory/hosts
Add configs for the new/updated South Africa instance.
=> Add South Africa configs

inventory/host_vars/www.openfoodnetwork.be/config.yml
This will fix the naked domain for BE, which now returns ERR_EMPTY_RESPONSE.
=> Serve www and naked BE domains with the same cert

inventory/group_vars/za.yml
Changing timezone from Johannesburg to Pretoria because Rails complained.
FYI if anyone ever needs to find out which timezones are valid, you can use this in rails console: `ActiveSupport::TimeZone.all.collect(&:name)`, which gives this list:
```
["American Samoa", "International Date Line West", "Midway Island", "Hawaii", "Alaska", 
"Pacific Time (US & Canada)", "Tijuana", "Arizona", "Chihuahua", "Mazatlan", 
"Mountain Time (US & Canada)", "Central America", "Central Time (US & Canada)", 
"Guadalajara", "Mexico City", "Monterrey", "Saskatchewan", "Bogota", "Eastern Time (US & Canada)", 
"Indiana (East)", "Lima", "Quito", "Atlantic Time (Canada)", "Caracas", "Georgetown", "La Paz", 
"Santiago", "Newfoundland", "Brasilia", "Buenos Aires", "Greenland", "Mid-Atlantic", "Azores", 
"Cape Verde …
```
=> Fix timezone issue for South Africa

inventory/host_vars/openfoodnetwork.ca/config.yml
This could potentially fix
https://github.com/openfoodfoundation/openfoodnetwork/issues/3937.
Chances are however, that we also need https://github.com/openfoodfoundation/ofn-install/pull/436.
=> Increase Unicorn timeout for Canada

inventory/host_vars/openfoodnetwork.ca/config.yml, inventory/hosts
=> Permanent configs for the new Canada server

inventory/host_vars/openfoodnetwork.de/config.yml
I've provisioned this already, just updating the code here.
=> Fix www redirects on Germany production

inventory/group_vars/all.yml, inventory/host_vars/local.ofn.org/config.yml
=> Remove old host_vars no one uses anymore

inventory/host_vars/prod2.openfoodnetwork.org.au/config.yml
This is the config used during the last deploy.
=> Au updates

roles/deploy/tasks/deploy.yml
Fixes an issue with assets being missing briefly during deployment as originally noted here: https://github.com/openfoodfoundation/ofn-install/pull/471#pullrequestreview-262141281
Back to zero-downtime (tested and working) :+1:
=> Fix missing assets for 10 seconds on deploy

.travis.yml, Vagrantfile, bin/requirements.yml, inventory/group_vars/all.yml, playbooks/provision.yml, roles/datadog/templates/stats.conf.j2, roles/dbserver/tasks/main.yml
This PR adds some replication settings and a postgres module to enable the use of data streaming...
With this change the replication is "ready" but not actually active.
=> Data streaming

roles/common/handlers/main.yml, roles/common/tasks/main.yml, roles/common/templates/memcached.conf.j2
Closes #509
Increases `memcached` memory from 64 to 128 MB, and max threads from 4 to 6.
=> Update memcached config

inventory/hosts
=> Add "all-prod" group for all production servers

roles/brotli_nginx/tasks/build.yml
Solves the first part of #516.
=> 516 Better parsing of the nginx version number

inventory/hosts
Adds an `all-staging` group for deploying/provisioning :rocket:
=> Add all-staging group

roles/deploy/tasks/deploy.yml
=> Fix lint issue in CI build

bin/requirements.yml
It brings improvements, fixes and features. Check out their changelog: https://github.com/DataDog/ansible-datadog/blob/master/CHANGELOG.md
=> Bump up Datadog role from 2.4.0 to 3.1.0

inventory/host_vars/openfoodireland.eu/config.yml, inventory/hosts
=> Remove unused Ireland entry from ofn-install

inventory/host_vars/prod2.openfoodnetwork.org.au/config.yml
Anticipating difficulties with reports.
=> Increase AU timeout from 2min to 6min for Xmas

roles/deploy/tasks/deploy.yml, roles/shared_handlers/handlers/main.yml
2-minute PR to improve deployments. Switches some tasks around to reduce downtime to a minimum.
Needs testing on staging.
=> Better deployments

inventory/hosts
Reverts openfoodfoundation/ofn-install#564
=> Revert "Remove AU production server from the prod list"

roles/migrate_assets/tasks/push_assets.yml
Closes #577 
Sets the correct user and group on uploaded asset files.
=> Set user and group of uploaded files when using rsync module

inventory/host_vars/www.openfoodnetwork.org.uk/config.yml
The swap has already been removed by Pau, we're just making sure it doesn't come back during next provision.
=> Remove UK swap from configs

inventory/host_vars/www.openfoodnetwork.org.uk/config.yml
:unicorn::unicorn::unicorn::unicorn::unicorn:
=> Increase UK Prod unicorn workers to 5

inventory/host_vars/openfoodnetwork.ca/config.yml
=> Increase Canada timeouts to 360

inventory/group_vars/all.yml, playbooks/letsencrypt_proxy.yml, roles/webserver/defaults/main.yml
Prep for https://github.com/openfoodfoundation/openfoodnetwork/issues/5418 (and general improvement for future production server migrations).
Automates a tricky part of the process of migrating a live production server. 
This was quite a messy job before, and a bit hacky. It's critical for doing easy server migrations.
=> Lets hack letsencrypt

inventory/host_vars/staging.openfoodnetwork.org.uk/config.yml
This will help (a lot) @filipefurtad0 test subscriptions in the rails 4 version.
=> Grant filipe access to uk staging

roles/deploy/tasks/deploy.yml
Closes #636 
Doing a restart seems to be enough to resolve the issue in #636. We can investigate issues with the new reload methods some other time.
=> Switch back to restarting unicorn on deploy

roles/deploy/handlers/main.yml
Catches a second case of possible duplicate entries in the crontab.
=> Whenever cleanup adjustment

inventory/group_vars/fr.yml, inventory/host_vars/staging.coopcircuits.fr/config.yml, inventory/hosts
We will switch to out new domain this week, on Wednesday night, so let's first do it for the staging server.
=> Add new configuration for new FR_staging domain

inventory/host_vars/_example.com/config.yml, inventory/host_vars/openfoodnetwork.de/config.yml, inventory/host_vars/openfoodnetwork.org.au/config.yml, inventory/host_vars/www.openfoodnetwork.org.uk/config.yml, roles/app/defaults/main.yml, roles/app/templates/application.yml.j2
https://github.com/openfoodfoundation/openfoodnetwork/pull/5729 will define these settings in the code and we will have the same Paperclip styles on all instances.
=> Remove image config which is now handled by OFN code

inventory/host_vars/openfoodbrasil.com.br/config.yml
=> Add attachment_url for Brasil

inventory/host_vars/app.katuma.org/config.yml, inventory/host_vars/openfoodnetwork.net/config.yml, inventory/host_vars/openfoodnetwork.org.au/config.yml, inventory/host_vars/staging.katuma.org/config.yml, inventory/host_vars/www.coopcircuits.fr/config.yml, inventory/host_vars/www.openfoodnetwork.org.uk/config.yml, roles/app/templates/application.yml.j2
This beta testers group is used as the base for a feature toggle. See https://github.com/openfoodfoundation/openfoodnetwork/pull/6536 for details.
=> Define beta_testers user emails

inventory/host_vars/www.coopcircuits.fr/config.yml
Closes
https://github.com/openfoodfoundation/openfoodnetwork/issues/6708.
It's not the most elegant solution because future added/removed managers won't be taken into account but it gets the job done now.
=> Toggle customer balance to French hub's managers

inventory/host_vars/www.coopcircuits.fr/config.yml
This opens the gates to `:customer_balance` feature toggle for all users in France. Based on https://github.com/openfoodfoundation/openfoodnetwork/pull/6801.
=> Enable feature toggles to entire FR instance

roles/db_transfer/tasks/main.yml
Reverts openfoodfoundation/ofn-install#701
=> Revert "Added became root on db_tranfert task to grant access of private key …"

inventory/host_vars/openfoodnetwork.ca/config.yml, inventory/host_vars/openfoodnetwork.net/config.yml
Related to https://github.com/openfoodfoundation/openfoodnetwork/issues/6802
:unicorn::unicorn::unicorn:
=> Bump US and CA to three unicorn workers

inventory/host_vars/www.openfoodnetwork.org.uk/config.yml
Following #704, toggles customer balances for UK prod.
Related to: https://github.com/openfoodfoundation/openfoodnetwork/issues/7058
=> Toggle customer balances for UK

inventory/group_vars/all.yml
I cant really support the deployment of this PR to the servers but this is the change needed.
=> Upgrade to ruby258

inventory/group_vars/us.yml
=> Add es to available locales in US config

inventory/host_vars/staging.openfoodnetwork.org.uk/config.yml
We're temporarily using anonymised CA data on UK Staging for testing additional taxes...
=> Update UK Staging configs

bin/requirements.yml
Related to https://github.com/openfoodfoundation/ofn-data/issues/50
Bumps wal2json role to newer version.
=> Update wal2json role

inventory/group_vars/all.yml, roles/compatibility/tasks/main.yml
- Installs Ruby 2.5.9
- Compiles it with jemalloc
=> Compile Ruby with Jemalloc in production

inventory/group_vars/all.yml, roles/deploy/tasks/deploy.yml
Pairs with https://github.com/openfoodfoundation/openfoodnetwork/pull/7737
I left 2.5.8 in the list just because the upgrade is very recent, I am not sure this is necessary.
=> Upgrade to ruby 2.7.3

playbooks/deploy_with_maintenance.yml
We obviously haven't used this playbook for a while! :eyes:
=> Remove old product cache rake task

inventory/group_vars/de.yml, inventory/group_vars/es.yml, inventory/group_vars/fr.yml
These messages are applied when "maintenance mode" is used. The default message is in English and it's not translatable via Transifex.
Default message: `The site is currently undergoing temporary maintenance. Please check back soon.`
=> Add maintenance mode messages

inventory/host_vars/_example.com/config.yml, inventory/host_vars/openfoodnetwork.org.au/config.yml, roles/app/tasks/main.yml, roles/app/templates/env.j2, roles/deploy/tasks/deploy.yml
Provisions configs to a **Dotenv** file per environment
To test this in Staging we'll need to provision with this PR then deploy https://github.com/openfoodfoundation/openfoodnetwork/pull/7745 and see if the ENV vars are okay.
=> Dotenv ofn-install

inventory/host_vars/staging.openfoodnetwork.org.au/config.yml, inventory/host_vars/staging.openfoodnetwork.org.uk/config.yml
All staging servers are now on Postgres 10 :+1:
=> Staging config updates

inventory/group_vars/all.yml, inventory/host_vars/coopcircuits.fr/config.yml, inventory/host_vars/openfoodnetwork.be/config.yml, inventory/host_vars/openfoodnetwork.ie/config.yml, inventory/host_vars/openfoodnetwork.in/config.yml, inventory/host_vars/openfoodnetwork.net/config.yml, inventory/host_vars/openfoodnetwork.org.uk/config.yml, inventory/host_vars/openfoodnetwork.org.za/config.yml, inventory/hosts
Updates configs to redirect from `www` to bare domain.
Fixes #643.
=> www redirect

inventory/group_vars/uk.yml, inventory/host_vars/staging.openfoodnetwork.org.uk/config.yml
Closes: #782 
Add the new Welsh language translation to OFN UK.
=> Add Welsh language to OFN UK Prod

inventory/group_vars/all.yml
=> Install Ruby 3.0.3

inventory/group_vars/fr.yml
Closes #https://github.com/openfoodfoundation/ofn-install/issues/796.
=> Remove italian from available_locales for FR config

inventory/host_vars/app.katuma.org/config.yml, inventory/host_vars/coopcircuits.fr/config.yml, inventory/host_vars/openfoodnetwork.net/config.yml, inventory/host_vars/openfoodnetwork.org.au/config.yml, inventory/host_vars/openfoodnetwork.org.uk/config.yml, roles/app/templates/application.yml.j2, roles/app/templates/env.j2
Removing unused functionality. Partnered with https://github.com/openfoodfoundation/openfoodnetwork/pull/7806.
This will create a merge conflict with https://github.com/openfoodfoundation/ofn-install/pull/751.
=> Remove unused feature toggle configuration

inventory/host_vars/openfoodnetwork.org.au/config.yml
=> Remove obsolete Australian variables

Vagrantfile, bin/requirements.yml, inventory/group_vars/_example.yml, inventory/group_vars/vagrant.yml, playbooks/provision.yml, playbooks/setup.yml
A little bit of maintenance work while I'm working on the New Zealand setup.
=> Updates for Ubuntu 20 and improved Vagrant setup

inventory/hosts
- #775
It's up and running on a new server.
=> Add nz-prod to globally managed servers

inventory/host_vars/coopcircuits.fr/config.yml, inventory/hosts, roles/brotli_nginx/defaults/main.yml, roles/brotli_nginx/tasks/build.yml, roles/common/tasks/main.yml
* Completes #825
I hit a few hurdles when provisioning a new server. These commits solve some of them.
=> Update fr-prod IP address to new server and more

inventory/host_vars/openfoodnetwork.ca/config.yml, inventory/host_vars/openfoodnetwork.net/config.yml, inventory/host_vars/openfoodnetwork.org.au/config.yml, inventory/host_vars/openfoodnetwork.org.uk/config.yml
Context: https://openfoodnetwork.slack.com/archives/C01T75H6G0Z/p1663927889996539
How to test: provision servers, and wait for 1 day and then check datadog
=> Disable Datadog/APM for UK, AU, CA and US

inventory/group_vars/all.yml, inventory/host_vars/_example.com/config.yml, inventory/host_vars/app.katuma.org/config.yml, inventory/host_vars/coopcircuits.fr/config.yml, inventory/host_vars/openfoodnetwork.be/config.yml, inventory/host_vars/openfoodnetwork.ca/config.yml, inventory/host_vars/openfoodnetwork.de/config.yml, inventory/host_vars/openfoodnetwork.hu/config.yml, inventory/host_vars/openfoodnetwork.ie/config.yml, inventory/host_vars/openfoodnetwork.net/config.yml, inventory/host_vars/openfoodnetwork.org.au/config.yml, inventory/host_vars/openfoodnetwork.org.nz/config.yml, inventory/host_vars/openfoodnetwork.org.uk/config.yml, inventory/host_vars/staging.coopcircuits.fr/config.yml, inventory/host_vars/staging.openfoodnetwork.org.au/config.yml, inventory/host_vars/staging.openfoodnetwork.org.uk/config.yml, roles/db_integrations/tasks/main.yml
This is an alternative to https://github.com/openfoodfoundation/ofn-install/pull/832.
closes #822 
I think that this works but I couldn't test it yet. I accidentally upgraded postgresql on au-staging and the new version doesn't seem to be supported by our role. We need to fix the db_integrations playbook.
=> N8n support

roles/datadog/tasks/main.yml
Finally I can provision again.
=> Remove another old apt source without valid key

inventory/group_vars/au.yml, inventory/group_vars/be.yml, inventory/group_vars/br.yml, inventory/group_vars/ca.yml, inventory/group_vars/co.yml, inventory/group_vars/de.yml, inventory/group_vars/es.yml, inventory/group_vars/fr.yml, inventory/group_vars/us.yml, inventory/host_vars/openfoodnetwork.org.au/config.yml, playbooks/deploy_with_maintenance.yml, playbooks/development.yml, playbooks/postgres_upgrade.yml, playbooks/provision.yml, playbooks/remove_ssh_keys.yml, roles/app_user/templates/sudoers.j2, roles/deploy/tasks/deploy.yml, roles/shared_handlers/handlers/main.yml, roles/webserver/templates/unicorn_environment.j2
I just deployed the latest release and saw the red error message about unicorn again. This error noise is either stressful or makes us ignore real errors. So I removed it.
=> Remove remaining unicorn service handling

README.md
This covers more things that were covered in the wiki. Now the wiki can simply link to this section. (_**update to wiki required on merge**_)
Alternatively, we could move this content to the wiki and link to it there.
Best viewed with whitespace ignored.
=> Add more detail for setup

inventory/host_vars/openfoodnetwork.org.au/config.yml
I'm using the zapier user, because it was quicker than creating a new one ;)
=> Add custom HBA entry to connect Metabase to au-prod database

README.md
Adds link to the wiki on deployment with Ansiable
=> Adds link to the wiki on deployment with Ansible

inventory/host_vars/openfoodnetwork.net/config.yml
* Closes #871 
I ran this already.
=> Allow more time to clone big order cycles

inventory/group_vars/cr.yml, inventory/host_vars/pruebas.laferia.cr/config.yml, inventory/hosts
Costa Rica Staging server information
=> Adds CR staging information

inventory/group_vars/in.yml
Depends on https://github.com/openfoodfoundation/openfoodnetwork/pull/11856
=> Use hi locale

inventory/group_vars/in.yml
Since we merged https://github.com/openfoodfoundation/openfoodnetwork/pull/11957 we can use those languages in next release
=> Add ml Malayalam and pa Punjabi lang

inventory/group_vars/es.yml
Awaiting confirmation before merging:
Also should these keys be removed from Katuma?
* `dani <danypr92@gmail.com>`
* `enricostn`
=> Grant access for Mikel to Katuma

inventory/group_vars/all.yml, roles/app/templates/env.j2, roles/app/templates/postgresql.yml.j2, roles/app_user/templates/bash_profile.j2, roles/app_user/templates/defaults.j2, roles/app_user/templates/sudoers.j2
Because we [recently overwrote someone's config](https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1729869218627449?thread_ts=1729778650.822229&cid=CG7NJ966B).
=> Show a clear notice on files that are managed with ansible

inventory/hosts, roles/migrate_assets/defaults/main.yml, roles/migrate_assets/tasks/push_assets.yml
=> Small fixes

.github/workflows/build.yml, .python-version, ansible.cfg, bin/lint, bin/pyenv-install, playbooks/db_integrations.yml, playbooks/db_restore.yml, playbooks/deploy.yml, playbooks/deploy_with_maintenance.yml, playbooks/postgres_tuning.yml, playbooks/postgres_upgrade.yml, playbooks/provision.yml, playbooks/restore_backup.yml, playbooks/rollback.yml, requirements.txt
* Depends on https://github.com/openfoodfoundation/ofn-install/pull/978
I chose a version that aligns with Ansible 8 from the latest pull request.
=> Run ansible-lint on CI again

requirements.txt
=> Remove unnecessary dependency declarations

inventory/host_vars/openfoodnetwork.org.au/config.yml
Update `au-prod` with the VINE Api url.
=> [City OFN vouchers] Set the production VINE Api url

inventory/group_vars/all.yml, playbooks/setup.yml
=> Remove custom python interpreter path

inventory/group_vars/es.yml
We are adding basque to the katuma instance
=> Adding basque to the instance

inventory/group_vars/all.yml, roles/common/tasks/main.yml
Also remove an old reference to memcached and some superfluous code.
=> Remove support for Ubuntu 16

.github/ISSUE_TEMPLATE/server-migration.md
Based on experience on https://github.com/openfoodfoundation/ofn-install/issues/966
=> Simplify migration, without temp domain or temp proxy
