openfoodfoundation/ofn-install

roles/common/templates/monit.j2
This change of the monit config file should make the wrapper script `delayed_job.sh` obsolete.
@RohanM Can you check this on your local machine? I changed our servers and they started dj without problems. But I couldn't test the deployment (still need memory).
=> monit calling delayed_job without wrapper script

roles/app/tasks/main.yml
Although in https://github.com/openfoodfoundation/ofn-install/blob/master/roles/deploy/tasks/main.yml#L60 we have a step that symlinks the bugsnag config/initializer from the `config_path` to the app's config folder, there was no step at provisioning time that copied the template to `config_path`.
I do it this way because this is the pattern I see in `ofn-install` but it'd be much simpler to have the `config/initializer/bugsnag.rb` in OFN's repo and read the api key from an env var like any other regular Rails app. No need for any extra steps at provisioning and deploy time then.
=> Compile bugsnag's initializer template

inventory/group_vars/all.yml
This allows adding custom per-instance locations to the nginx config. Useful to try out ideas before merging them into OFN.
=> Include /etc/nginx/sites-available/ofn/* in nginx

inventory/host_vars/_example.com/secrets.example.yml
**What** **Why**
On running the OFN-install scripts OFN requires a Google Maps API key to correctly configure.
There is no other mention in the Wiki so this seems like the most appropriate place to ensure the user knows to include.
=> Add maps api key to secrets.yml

inventory/host_vars/_example.com/config.yml, inventory/host_vars/_example.com/secrets.example.yml, roles/unicorn_user/templates/defaults.j2
Closes #120 
As described in https://www.skylight.io/support/advanced-setup#enabling-additional-environments, by setting `SKYLIGHT_AUTHENTICATION`, we'll enable skylight to gather instrumentation data in production. 
`skylight_authentication` has been set as secret already in https://github.com/coopdevs/katuma_secrets/pull/1 and https://github.com/coopdevs/katuma_secrets/pull/2 for Katuma.
Once we get this working other instances can set their own.
=> Provide SKYLIGHT_AUTHENTICATION to unicorn user

roles/deploy/handlers/main.yml, roles/deploy/tasks/main.yml
This ensures new Spree configuration values will be picked up. In any case, it's safer to restart the services at the end of the deployment so we don't miss any configuration or code to be reloaded.
Apart from that, it's simpler to make it restart rather stopping and relying on monit to bring it up.
=> Restart delayed job after running db:seed

bin/requirements.yml, inventory/group_vars/all.yml, inventory/host_vars/local_vagrant/config.yml, playbooks/provision.yml, roles/cert/tasks/main.yml
So, it seems that in the role that we're using now there is no support for the nginx plugin for renewal https://github.com/geerlingguy/ansible-role-certbot/issues/2#issuecomment-365369540
Since this is something that we need to address ASAP we created an [Ansible role](https://github.com/coopdevs/certbot_nginx) to just:
1. Install `certbot` and `nginx` plugin
2. Generate the certificate if needed
We also remove our `cert` role since it's just creating confusion. It was generating the certificate, let's do that in the external role (same strategy as geerling's role)
Solves https://github.com/openfoodfoundation/ofn-install/issues/86
Solves https://github.com/openfoodfoundation/ofn-install/issues/105
Supersedes https://github.com/openfoodfoundation/ofn-install/pull/117
=> Use coopdevs role to install certbot and nginx plugin

Vagrantfile
The default catalogue moved and this image is not found on
atlas.hashicorp.com any more. Older versions of vagrant still try
to access the old server and need the URL explicitely.
=> Add URL to vagrant image

roles/webserver/templates/unicorn.service.j2
Otherwise, Unicorn cannot see this env var and Skylight reports a "authentication token required".
=> Specify SKYLIGHT_AUTHENTICATION in systemd unit

inventory/host_vars/_example.com/secrets.example.yml, roles/app/defaults/main.yml, roles/app/tasks/main.yml, roles/app/templates/application.yml.j2, roles/deploy/defaults/main.yml, roles/deploy/tasks/main.yml
Closes #170.
Making sure we actually provision the env vars we need, and updating the example `secrets.yml` file to make it clearer what should be in there.
=> Missing environment variables for Stripe and S3

README.md
It is a chore to keep the credits section up to date when many people
are contributing. In times of Git and Github, we don't need to bother
about manually updating an author list, because it can be generated
automatically.
=> Remove outdated credits section

inventory/host_vars/_example.com/secrets.example.yml, roles/unicorn_user/templates/defaults.j2
Closes #202. 
Enables mail settings for from_address and bcc to be set. These are currently able to be set in the instance config section, but get wiped after each deploy.
This PR has a corresponding PR in the main repo: https://github.com/openfoodfoundation/openfoodnetwork/pull/2482 
They should both be able to be merged separately without any problems.
=> Add mail method settings

roles/bundler/tasks/main.yml
The bundler install was always run, even if already present. This adds a check for it's success, removes an unnecessary step and makes sure that we install bundler for the right ruby version.
=> More efficient bundler install

roles/common/handlers/main.yml, roles/common/tasks/main.yml, roles/common/templates/monit.j2, roles/deploy/handlers/main.yml, roles/deploy/tasks/main.yml, roles/webserver/defaults/main.yml, roles/webserver/tasks/main.yml, roles/webserver/templates/delayed_job.service.j2
Closes #84 and #179. And probably #119.
This PR adds a new systemd unit for managing our delayed_job processes. It also removes the monit package which is now no longer needed, as systemd is now configured to restart the service when it is not running.
It is usable as a regular service e.g: `sudo systemctl restart delayed_job_openfoodnetwork.service`. The tasks that start/reload delayed_job have been switched to use this service instead of the directly running the script. 
I've also added a new task to run `systemctl daemon-reload` to reload the config after any systemd files have been updated, because they won't work otherwise.
=> Delayed job systemd unit

roles/deploy/handlers/main.yml
Although we were passing RAILS_ENV when updating cron jobs through
`whenever --update-crontab`, it turns out that `production` is the
default value for the `:environment` argument.
I spotted this while investigating why we had 9 failed `db2fog:backup`
cron jobs reported in Bugsnag for production. That was impossible as we
didn't provision production in a very long time although we did in
staging.
The problem was that `crontab -l` in staging returned something like:
```
0 * * * * /bin/bash -l -c 'cd /home/openfoodnetwork/apps/openfoodnetwork/current && RAILS_ENV=production bundle exec rake openfoodnetwork:cache:check_products_integrity --silent'
```
Thus, these jobs were executed as if they were in production.
=> Specify the Rails env when updating cron jobs

inventory/host_vars/_example.com/secrets.example.yml
When I looked at the code dealing with some variables, I found the examples inconsistent with the code for the case they are "not set". This should be more consistent now.
=> Update example secrets file

roles/language/handlers/main.yml, roles/language/tasks/main.yml
Moving the rebuild tasks into triggers means that they don't run unless
the language packages changed.
=> Trigger language rebuilding only when changed

inventory/group_vars/es.yml
In case either Dani or Enrico have a "stuck at the dentist" situation
while I'm on holidays.
Jokes aside, we decided with @Matt-Yorkley to let him use our staging
servers from now on as a proof-of-concept for our goal of
granting access for all sysadmins to all servers. This will let us spot
the bottlenecks and areas we will need to work on.
=> Add backup sysadmins to katuma servers

roles/unicorn_user/templates/sudoers.j2
Allow the openfoodnetwork user issuing systemd commands for the delayed
job service without password.
=> Allow unicorn user deal with delayed job

roles/dbserver/files/fix_pg_encoding.sh, roles/dbserver/files/fix_pg_encoding.sql, roles/dbserver/tasks/main.yml
Using the script module combines our three steps in one. This is simpler
and more robust.
This script will still run every time.
=> Use Ansibles's script module instead of copying

inventory/group_vars/uk.yml
In case UK sysadmins are "stuck at the dentist" and there's an emergency on production.
=> Add more backup sysadmins to UK servers

inventory/group_vars/all.yml
Closes #216. 
Removes the HSTS header to ensure it doesn't get written twice by nginx and Rails, resulting in an invalid value.
Also removed an old commented-out header line.
=> Remove HSTS header and old unused header

inventory/group_vars/uk.yml
Our locale variable was outdated on ofn-install. It looks like it was manually changed on the server, but recently got overwritten with the old variable when I provisioned UK prod, so we lost localised translations for `en_GB`.
=> Fix locale for UK servers

inventory/group_vars/all.yml
This small change enables HTTP/2
If someone deploys on Debian, you might want to check if it still has issue with OpenSSL version https://sergii.rocks/feed/post/nginx-http2-with-alpn-on-debian-8-jessie
I deploy to Ubuntu 16.04 LTS running in [LXD](https://linuxcontainers.org/lxd/) container and it works just fine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openfoodfoundation/ofn-install/110)
=> enable HTTP/2 in nginx config

inventory/group_vars/all.yml
This isn't really part of an issue or an epic, but we talked about how it would be nice to have.
This enables copy-pasting of a PR's name from a Github page so you don't have to type the repo and branch name out separately in two places, for example when staging things for testing.
**Copy:** 
**Paste:**
P.S. I'm not invoicing for this one, just wanted to add this to make staging PRs a bit nicer. :heart:
=> Enable copy-paste of PR name from Github

playbooks/remove_unwanted_packages.yml
The packages in this commit are present in Rimu Hosting images.
This solves #198. The errors I saw were caused by nginx not being able to run, because apache was using port 80 already.
I thought about including this in the main provisioning process. The packages could be defined as variables. But the packages don't depend on the OFN instance we want to install, they depend on the target machine and if other software is supposed to run there.
Do you have better ideas how to handle this problem?
=> Add optional playbook to remove unwanted packages

roles/webserver/tasks/main.yml
Just a quick improvement to the way we refresh systemd configs. 
It should happen: 
- immediately after updating init scripts
- before we call any more services
- only if our init scripts have been changed.
=> Only reload systemd when init scripts change

inventory/host_vars/_example.com/config.yml, playbooks/provision.yml
Closes #235.
Allows for registering multiple subdomains with letsencrypt by specifying a list. 
The `-d` flag in the certbot certificate command can take a comma-separated list, so we use this. Defaults to the existing `domain` variable if the list is undefined.
=> Allow multiple domains with certbot

bin/requirements.yml, inventory/group_vars/all.yml, inventory/host_vars/_example.com/config.yml, playbooks/provision.yml
This can be very useful to avoid running out of memory. It may be that a
server only needs more memory during deployment.
I have been setting this up manually in the past. It would be nice to automate.
=> Add option to create a swapfile

inventory/host_vars/_example.com/secrets.example.yml, roles/unicorn_user/templates/defaults.j2
Since https://github.com/openfoodfoundation/openfoodnetwork/pull/2583/ we can set some encryption for email.
=> Support mail via TLS

inventory/host_vars/openfoodnetwork.net/config.yml
Closes: #169
The mail domain is needed for provisioning to run. Otherwise we get:
```
TASK [unicorn_user : Write OFN environment variables defaults] ****************************************************************************************************************************************************
Monday 27 August 2018  12:17:18 +1000 (0:00:00.034)       0:03:17.723 ********* 
fatal: [openfoodnetwork.net]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'mail_domain' is undefined"}
```
=> Add required mail_domain to us host config

.travis.yml
The current version of jdauphant.nginx is not compatible with Ansible
2.7.0. The error was:
> 
>   ERROR! 'always_run' is not a valid attribute for a Handler
> 
>   The error appears to have been in
>   '/home/travis/build/openfoodfoundation/ofn-install/community/jdauphant.nginx/handlers/main.yml':
>   line 17, column 3, but may
>   be elsewhere in the file depending on the exact syntax problem.
=> Install compatible Ansible version on Travis

inventory/group_vars/au.yml, inventory/group_vars/de.yml, inventory/group_vars/es.yml, inventory/group_vars/fr.yml, inventory/group_vars/uk.yml, inventory/group_vars/us.yml
Closes #180 
If there's a production issue in any of the OFN instances any Ha or Ri
dev can put the sysadmin hat on and fix it.
Access to production machines is also needed to investigate production
logs as well as production data when trying to fix high severity issues,
like happened recently.
=> Add Ha-Ri core team devs SSH key to all servers

roles/dbserver/templates/pgpass.j2
Some Postgresql commands don't connect to a database. If our pgpass file
specifies a database, the password can't be used by those commands. By
defining `*` for any database, we can use any Postgres tool on the
command line without a password. The potential of conflict is minimal as
we would choose another database user if we wanted to separate access
scopes to databases.
These commands need to be passwordless for deployment scripts.
=> Enable passwordless createdb and dropdb

inventory/host_vars/openfoodnetwork.net/config.yml
Asset compilation failed, probably because it ran out of memory.
=> Install swap file on US server

bin/requirements.yml
Closes #207 
This contains https://github.com/jdauphant/ansible-role-nginx/commit/8f2b741a9ab3465cc7f64881c3f873e06c828099 which fixes #207. Check https://github.com/jdauphant/ansible-role-nginx/compare/v2.7.4...v2.8.1 for the full list of changes. I think it's safe to update.
=> Update jdauphant.nginx from v2.7.4 to v2.8.1

inventory/group_vars/all.yml, inventory/host_vars/alpha.katuma.org/config.yml, playbooks/provision.yml
This change gives support for serving multiple subdomains from the same nginx server using HTTPS. 
This solves the problem of having to migration from alpha.katuma.org to app.katuma.org. This has been long overdue and we need it to improve the perception potential customers have about the project. It's been already a year passed the alpha!
This will be useful for other instances facing a similar problems due to increased flexibility.
This introduces the `server_name` var as a way to provide a nginx server name other than the domain plus the `certbot_cert_name` var to allow also setting a certificate name other than the domain.
Note this depends on https://github.com/coopdevs/certbot_nginx/pull/7.
I carefully ordered the commits so you can follow easily. Check them if there's something you …
=> Serve multiple subdomains

inventory/host_vars/staging.openfoodfrance.org/config.yml, inventory/host_vars/www.openfoodfrance.org/config.yml
Increasing timeouts for FR servers due to issue: https://github.com/openfoodfoundation/openfoodnetwork/issues/3148
Same as #238
This change is already done in prod manually:
vim /home/openfoodnetwork/apps/openfoodnetwork/shared/config/unicorn.rb
/etc/init.d/unicorn_openfoodnetwork restart
vim -> change timeout from 30 to 90
=> Increase FR timeouts

bin/requirements.yml, inventory/host_vars/_example.com/secrets.example.yml, playbooks/provision.yml
This uses https://github.com/DataDog/ansible-datadog to install the agent with the provided `datadog_key`. Note this variable needs to specified in the secrets file for the agent to work.
Note you will need to execute `ansible-galaxy -r bin/requirements.yml install` before provisioning to fetch this new role.
=> Install datadog agent in provisioning

inventory/host_vars/alpha.katuma.org/config.yml
Until we don't set up a new 8Gb-RAM new server, which is going to happen this month, this will let us sleep.
:point_up: This is its usage under regular conditions
=> Enable 1G swap file on Katuma

inventory/hosts
We just added the subdomain app.katuma.org to serve the app besides the old alpha.katuma.org. We want to get rid of the *alpha*ness of that URL so people don't get the wrong impression. For now, Nginx serves both.
=> Replace FQDN in inventory with new app.katuma.org

playbooks/provision.yml
That is what ansible-lint complains about. It fixes the build error
```
$ ansible-lint site.yml --exclude=community
[601] Don't compare to literal True/False
/home/travis/build/openfoodfoundation/ofn-install/playbooks/provision.yml:21
when: swapfile_size != false
The command "ansible-lint site.yml --exclude=community" exited with 2.
```
There is no need to conditionally execute the swapfile role. It will skip all tasks if no `swapfile_size` is defined.
=> Don’t compare to boolean literal

playbooks/provision.yml, roles/deploy/handlers/main.yml, roles/deploy/tasks/main.yml
Just that. It displays the following message in the #devops-notifications channel of our Slack.
when deploying and provisioning. Note that the message will tell what action was taken, either deploy or provision.
This will provide greater visibility to the whole team, not just the person executing ansible or devs.
=> Notify Slack on deploy and provision

bin/requirements.yml
The only relevant change I found is https://github.com/Oefenweb/ansible-swapfile/commit/ca4ef15d2419b8582f13a3c7b4e027372d539c68.
Also, this update includes support for Ubuntu 18.04.
=> Update oefenweb.swapfile from v2.0.7 to v2.0.14

playbooks/development.yml, playbooks/provision.yml, roles/bundler/tasks/main.yml, roles/deploy/tasks/main.yml
Closes https://github.com/openfoodfoundation/ofn-install/issues/74.
https://openfoodnetwork.slack.com/archives/C0DNLAZC7/p1546618893018000
Installing during deploy instead of provision enables us to read the
Gemfile.lock file which contains the last used bundler version.
The newest bundler v2 doesn't support our Ruby 2.1.5. We need to install
an older bundler.
This depends on https://github.com/openfoodfoundation/openfoodnetwork/pull/3302 for the install script.
=> Install used bundler version on deploy

bin/requirements.yml
Related to #324
This installs cerbot v0.28 needed to stop using TLS-SNI-01 as described
in https://community.letsencrypt.org/t/how-to-stop-using-tls-sni-01-with-certbot/83210.
=> Update certbot_nginx from 0.0.1 to 0.0.3

roles/app/tasks/main.yml, roles/app/templates/application.yml.j2, roles/app/templates/bugsnag.rb.j2, roles/deploy/tasks/main.yml
This has been moved to the app's `config/initializers/` instead where it doesn't need neither templates nor symlink. It's just about providing the BUGSNAG_API_KEY env var, which is set in both the unicorn service and `/etc/default/openfoodnetwork`.
As a result, it'll fix the issue that both Katuma and OFF are facing where the `config/initializer/bugsnag.rb` symlink to `shared/config/bugsnag.rb` does not exist thus, nothing gets notified to Bugsnag since December 3rd (according to customer support).
=> Remove all traces of bugsnag initializer

playbooks/provision.yml, roles/deploy/handlers/main.yml
I've been playing with a Vagrant dev setup that we might use for an OFN UK hackday and realised that we probably don't need to notify Slack every time a Vagrant box is updated. :trollface:
=> Dont spam Slack when provisioning vagrant dev boxes

inventory/hosts
This removes the old server from the inventory. Ansible complains that it is unreachable when provisioning.
=> Remove old staging1.openfoodnetwork.com.au

inventory/group_vars/be.yml
Last time we deployed a custom branch based on v1.27.0 plus nl_BE but it was one-time change that needs to be persisted here.
Now Theo complains the server lost its nl_BE translation. See https://openfoodnetwork.slack.com/archives/CFU9N7TGB/p1552397538005900
=> Enable nl_BE locale for the Belgian instance

roles/app/templates/application.yml.j2
Without this conditional checks if you don't have these services set up the provisioning will fail. IMO having backups and error tracking shouldn't be optional but decoupling this discussion from the
provisioning will buy some time.
Without it at least the German instance can't be provisioned (I bet they don't have Bugsnag at least). This is exactly what Brandy had to deal with in https://openfoodnetwork.slack.com/archives/C0DNLAZC7/p1552393240006500. Fortunately, she managed to get it working.
**This still needs to be tested in staging**
=> Make S3 and Bugsnag optional

roles/semaphore_deployment/tasks/main.yml, roles/semaphore_deployment/templates/deploy.j2
I havn't tracked my time for this as it's not been prioritised, it was a 5-minute job, but I think this could save a lot of time when we make important updates to ofn-install.
Staging servers that have Ansible installed locally for deploying themselves via Semaphore can now also update their local copy of ofn-install by pulling from the repo, and upgrade their community roles if the versions have been bumped in the `requirements.yml` file.
=> Set staging servers to update themselves

roles/deploy/tasks/main.yml
Closes #345
I've changed the order of a few of these tasks so that we don't get fatal error on a fresh install.
=> Fix fatal missing database errors when doing a fresh install

bin/setup
The setup script installs our community modules but does not update them if the versions have been bumped. 
I've added this quick change as I think we'll need to update the community modules on various servers soon, including the local ansible installs of our staging servers that use Semaphore deployments, and it'll be much easier if this script actually works. :+1:
=> Add --force flag to community modules update script

playbooks/setup.yml
Closes #349 
Ensures that ssh keys are added to the `ofn-admin` user during setup, to avoid a fatal error during provisioning on a fresh install.
=> Fix missing keys on fresh install

Vagrantfile, bin/requirements.yml, playbooks/provision.yml, roles/common/tasks/main.yml, roles/compatibility/tasks/main.yml
Reverts openfoodfoundation/ofn-install#359
Closes #343
Closes #344
This pull request was initially opened by @Matt-Yorkley in #342. It was approved already.
This PR bring compatibility for Ubuntu 18 (Bionic Beaver) to ofn-install. I've tested the setup, provision, and deploy playbooks with these changes on both Ubuntu 16 and Ubuntu 18 boxes. Both are running fine, and the fatal errors are fixed for Ubuntu 18.
Additional notes are in the 2 issues above.
Note: this requires an update of the community roles with:
`ansible-galaxy install -r bin/requirements.yml --force`
=> Bionic beaver - take 2

playbooks/deploy.yml, playbooks/provision.yml, roles/check_secrets/tasks/main.yml
Closes #365 
Provision and deploy playbooks will now exit early if the secrets have not been included correctly.
Tested (both paths) on Vagrant.
=> Check secrets have been included

roles/semaphore_deployment/tasks/main.yml
I've successfully run this task on staging servers without any problems, but I've had an error once or twice whilst testing this during the Bionic Beaver work, where the `bin/setup` script gave an error about the requirements file being missing.
This fixes the issue and should make it more consistent, by adding the `chdir` argument to the task to make sure ansible is in the `/ofn-install` folder when it runs the `bin/setup` script.
=> Improve community roles install task for Semaphore deployment

roles/semaphore_deployment/tasks/main.yml
We hit an issue today with a staging server not recognising Ansible syntax because the version it had was incredibly old. This switches to using the latest version from the Ansible repo.
To update it, just run the `setup_semaphore_deployment.yml` playbook against any server that uses Semaphore.
@sauloperez
=> Use latest ansible in semaphore deployment

roles/app/tasks/main.yml, roles/app/templates/application.yml.j2, roles/app/templates/db2fog.rb.j2, roles/deploy/tasks/main.yml
Closes #280 
Removes the db2fog initializer from ofn-install after it is moved to the main repo in: https://github.com/openfoodfoundation/openfoodnetwork/pull/3694
This also frees up the `deploy.yml` playbook from all dependencies on secrets files, so deploying from the command line will be much simpler and deploying via Semaphore will not involve any secrets handling. :tada: 
openfoodfoundation/openfoodnetwork#3694
=> Remove db2fog initializer from ofn-install

roles/deploy/tasks/main.yml
Closes #321 
Keep the last 5 pairs of release files in `/releases-old` (backup and dump) and delete the rest when deploying.
=> Delete old files in /releases-old on deploy

playbooks/deploy.yml
Closes #371
As explained in https://github.com/openfoodfoundation/ofn-install/issues/371 we no longer need secrets while deploying so there is no need for this check anymore :tada:.
This should fix the last Semaphore deployment failure https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/fr-staging/deploys/8.
=> Do not check secrets as a requirement to deploy

inventory/host_vars/_example.com/secrets.example.yml, roles/app/templates/application.yml.j2
This allows for provisioning of different buckets for images and backups, and enables provisioning of the `Spree::Config['s3_bucket']` preference used for images, which was previously only accessible via the superadmin config page.
This is a partial patch for recent changes in #370 
**Configuration:**
The use of `s3_backups_bucket` variable is unchanged.
The new `s3_images_bucket` will populate the `Spree::Config[:s3_bucket]` preference which is used for images. Unless that variable is explicitly set in the secrets file, no existing manually configured settings will be changed.
=> Allow provisioning of different buckets

roles/app/tasks/main.yml
Closes #332
Added in https://github.com/openfoodfoundation/ofn-install/pull/329, it was meant to ensure said file gets removed from our servers. Merged back on Feb 28, all these servers have been provisioned and so UK, FR, Katuma, BE and DE servers do not have the file anymore. I checked it manually so we can remove it.
=> Remove already provisioned Bugsnag absence check

inventory/hosts
Closes #313 
Adds a `europe` group in the hosts file, so playbooks can be run against multiple servers at once.
Hot tip: you can test which servers would be included in a command by using `--limit europe` and `--list-hosts`.
=> Create europe group

roles/deploy/tasks/main.yml
This is equivalent to `--depth 1`, meaning we fetch only the latest version of each file and not the entire history. 
It reduces the execution time of this task from ~2:30 to ~0:40. :rocket:
=> Specify depth when fetching repo

playbooks/deploy.yml, roles/deploy/handlers/main.yml, roles/deploy/tasks/main.yml
We can now get notified when deployment fails as well as when it succeeds, using Ansible's block/rescue format in the `deployment.yml` playbook.
Tested on Vagrant (both success and failure paths).
=> Rescue and notify Slack when deployment fails

roles/deploy/tasks/main.yml
The Ansible git module doesn't play nicely with combining a custom refspec (which we need for accessing pull requests in Semaphore deployment) and the `--depth` flag, so we need to revert this and lose the speed increase.
=> Revert use of --depth

playbooks/postgres_tuning.yml
Closes #361 
This is a draft playbook to configure PostgreSQL for production servers by setting some recommended values.
It might be a good idea to get the Datadog paid plan first, as discussed here: https://community.openfoodnetwork.org/t/making-operations-a-first-class-citizen/1601/5
Then we could try provisioning this configuration to one production server and get some data on the results.
=> Configure postgres for production

playbooks/deploy.yml
We hit this issue the other day when Rachel was testing. It turns out the rescue block we use in deploy.yml to send a failed deployment alert to Slack interferes with the exit code of the playbook because of an Ansible bug. This fixes it.
See Ansible issue for more details: https://github.com/ansible/ansible/issues/48344
=> Ensure correct exit code on deployment

roles/app/tasks/main.yml, roles/app/templates/seed.sh.j2, roles/deploy/tasks/deploy.yml
Follow-up from: https://github.com/openfoodfoundation/ofn-install/pull/415#discussion_r277547914
We don't need tasks in multiple playbooks to get this job done :+1: 
The code that handles this rake task is in the `spree_auth_devise` gem, and it either takes input from `ENV` vars, or prompts for user input (which then hangs in Ansible).
=> Clean up db:seed task

inventory/group_vars/all.yml, playbooks/development.yml, roles/dbserver/tasks/main.yml, roles/dbserver/tasks/postgresql.yml
Closes #375 
> The pg_stat_statements module provides a means for tracking execution statistics of all SQL statements executed by a server. Source https://www.postgresql.org/docs/9.5/pgstatstatements.html
I chose to use the parameters showed at PostgreSQL docs in the "Configuration Parameters" section to start with.
It contains tons of useful aggregate data about the statements the DB runs. See the result of placing an order:
```sql
open_food_network_dev= SELECT query, calls, total_time, rows, 100.0 * shared_blks_hit /
nullif(shared_blks_hit + shared_blks_read, 0) AS hit_percent
FROM pg_stat_statements WHERE query not like '%pg_stat_%' ORDER BY total_time DESC LIMIT 5;
(...)
-[ RECORD 2 ]------------------------------------------------------------------------------------------------------- …
```
=> Enable pg stat statements

inventory/group_vars/all.yml
Closes #379
This will help diagnose the execution of the DB server. You know, you
better have a log file at hand when things go south...
It sends log messages to files like `postgresql-2019-04-19_183500.log`
in `/var/lib/postgresql/9.5/main/pg_log`. These per-day log files will
get overwritten on rotation, keeping a 3-month window always. Yes, it
turns out PostgrSQL has a built-in log rotation facility :muscle:.
I chose 3 months out of nothing. We need to see how fast the disk fills
up and adjust the value. I thought 3 months is more than enough data to
troubleshoot issues.
I also went with the default `pg_log` directory but it might be
interesting to log it to `/var/log/` in the future instead. According to
https://logdna.com/postgresql-logging-guide/:
> set this parameter to a value …
=> Enable capturing of PostgreSQL's stderr

roles/webserver/handlers/main.yml, roles/webserver/tasks/main.yml
While testing the new reload handler for reloading when the unicorn config file is updated, I realised we needed an extra step to avoid a fatal error when trying to reload before the service had been started on a fresh install.
The two-step handler I created to fix it wasn't correctly triggering the second step, so the error was fixed but the reload was not being triggered properly. It's fixed now.
=> Update unicorn reload handler

inventory/group_vars/all.yml, inventory/host_vars/_example.com/secrets.example.yml, playbooks/deploy.yml, playbooks/postgres_tuning.yml, playbooks/provision.yml, roles/datadog/handlers/main.yml, roles/datadog/tasks/main.yml, roles/datadog/tasks/nginx_stats.yml, roles/datadog/tasks/pg_stats.yml, roles/datadog/templates/dd-nginx.j2, roles/datadog/templates/dd-postgres.j2, roles/datadog/templates/logging.conf.j2, roles/datadog/templates/stats.conf.j2, roles/datadog/templates/status.conf.j2, roles/dbserver/tasks/main.yml, roles/shared_handlers/handlers/main.yml
Closes #305 
This PR: 
- improves our current Datadog settings
- notifies Datadog on a successful deploy or provision
- enables collection of postgresql stats and logs through the Datadog agent
- also enables nginx stats and logging to Datadog
:warning: Provisioning the new postgres stats and logging features to a server requires adding or updating these variables in `secrets.yml`:
```ruby
datadog_db_password: <secure_password_goes_here> # use $ openssl rand -hex 128
db_integrations:
- { user: datadog, state: present, password: "{{ datadog_db_password }}" }
```
And if you havn't done it already, you'll also need to run `playbooks/db_integrations.yml` first to create the database user and grant them permissions.
=> Datadog config

inventory/host_vars/_example.com/secrets.example.yml, roles/app/templates/application.yml.j2
No need to rely on the default region Db2fog might specify. Needed for https://github.com/openfoodfoundation/openfoodnetwork/pull/3763.
=> Allow passing a specific AWS region to S3 settings

inventory/host_vars/www.openfoodfrance.org/config.yml
Closes #395
Having 8 Gb of RAM there's plenty of room for increased concurrency. OFF's users will appreciate it.
Also, having a Datadog pro account we can closely watch the impact of this change on the system resources.
=> Set num. of Unicorn workers to 4 for FR production

roles/app/templates/application.yml.j2, roles/deploy/tasks/deploy.yml
Needed to resolve issues with Semaphore deployments, and some manual deployments (depending on local dev setup).
Moves variables defined in `secrets.yml` out of `deploy.yml`. 
The db:seed task needs those two ENV vars to be available, but we shouldn't reference them directly in `deploy.yml`, as we have decoupled it from `secrets.yml`.
=> Adjust ENV vars for db:seed 

roles/dbserver/tasks/main.yml
It seems like on some hosts the postgres user might not exist on a fresh install, which can cause an error here. I've switched the task order just to be safe.
=> Create log directory after postgres installation

inventory/host_vars/openfoodnetwork.de/config.yml
They need to work with thousands of products and our performance is quite bad. This config is in place right now and they are happy to wait "only five minutes" for a shopfront with 7000 products to load.
=> Increase workers and timeouts for Germany

playbooks/development.yml, roles/datadog/tasks/pg_stats.yml, roles/datadog/templates/dd-postgres.j2
Due to two issues, most of the Postgres Datadog graphs show empty now, especially those related to indexes.
The first is one is that we were creating neither the function nor the view Datadog needs because no database was passed to psql. The second one is that we manually need to specify the db relations we want to track in the Datadog's config file.
=> Fix postgres Datadog integration

inventory/group_vars/all.yml, inventory/host_vars/www.openfoodnetwork.org.uk/config.yml, playbooks/provision.yml
We had some reports of browsers intermittently failing to load the homepage when using the naked url `openfoodnetwork.org.uk`. At first it seemed to just be in Internet Explorer :nauseated_face: but it turned out to be intermittently affecting Firefox and Chrome as well. It turned out to be quite a critical issue, as multiple users were finding the site didn't load at all!
This seems to have resolved the problem on UK prod. It looks like France needs this as well, and probably others. We should double-check Katuma prod when provisioning this, as it has a setup with custom domains.
=> Ensure certificates are present for www and naked url

inventory/host_vars/app.katuma.org/config.yml
Apparently, server ate up almost all the swap while precompiling assets
for the deploy of
https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/v2.0.2,
as shown in
https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1559721636000600.
I feel ashamed but we have no resources to manage a server upgrade while
being busy with the v2 roll-out, the hiring of a new employee in Katuma
and other Coopdevs duties with the right focus. This will again buy some
more time.
=> Increase Katuma's available swap

bin/requirements.yml
Closes #392 
This fixes some issues with certbot on new servers.
=> Bump coopdevs.certbot_nginx role

inventory/group_vars/all.yml
We had several cases in which we wanted to increase the timeout to over a minute. While unicorn was running longer than a minute (e.g. `unicorn_timeout 120`), nginx was shutting down the connection after one minute. Now we have the same timeout for nginx and unicorn.
This is needed for Germany and Australia to keep the current configuration. France and UK also have a unicorn timeout of 120 configured and this change may fix some performance problems. When there are many requests, there can be a queue build-up. When the unicorn timeout is longer than the nginx timeout, unicorn will still be busy when nginx tries to pass on the next request.
=> Adapt nginx timeouts to unicorn configuration

playbooks/pull_assets.yml, playbooks/push_assets.yml, roles/migrate_assets/defaults/main.yml, roles/migrate_assets/tasks/main.yml, roles/migrate_assets/tasks/pull_assets.yml, roles/migrate_assets/tasks/push_assets.yml
Part of the Canada migration #339.
Playbooks for migrating all the static assets from one server to another.
~~Copies contents of OFN asset folders from one server to another recursively, by executing `scp` on the control machine using the `-3` flag: the user's machine will connect to both the source and destination via SSH and act as a mid-way point for the transfer.~~
My initial version of this was really slow. I've switched to using rsync via the `synchronise` module, and now it's 100 times faster. :tada:
=> Asset migration playbook and role

roles/language/tasks/main.yml
I saw the following warning:
Invoking "apt" only once while using a loop via squash_actions is
deprecated.
Newer versions of the apt module support lists directly and the use of
`with_items` is deprecated.
There are more of these warnings coming from community modules. They should go away when we update those modules.
=> Call apt with list of packages

inventory/group_vars/all.yml, playbooks/provision.yml, roles/brotli_nginx/tasks/main.yml
Related to https://github.com/openfoodfoundation/openfoodnetwork/issues/3858 and https://github.com/openfoodfoundation/openfoodnetwork/issues/#3860
Adds support for [Brotli](https://github.com/google/ngx_brotli) compression.
Tested on UK Staging.
=> Add Brotli compression support

inventory/group_vars/all.yml
Related to https://github.com/openfoodfoundation/openfoodnetwork/issues/3858 and https://github.com/openfoodfoundation/openfoodnetwork/issues/#3860
Enables gzip compression via nginx.
Tested on UK staging.
=> Add gzip compression to nginx configs

playbooks/temporary_proxy.yml, roles/temporary_proxy/tasks/main.yml
Related to #339, but useful for all server migrations.
This new playbook and role will direct the server to proxy all requests to the specified target. This is useful for redirecting traffic during a server migration. Running `provision.yml` again on the server will remove the temporary configuration. 
Use `-e "proxy_target=<ip-address>"` to specify the target.
Tested on UK staging. :heavy_check_mark:
=> Add new playbook and role for proxying

inventory/group_vars/all.yml
Maybe this got changed whilst resolving a merge conflict the other day? 
There's a missing semicolon in the nginx configs, and it's breaking the `provision.yml` playbook.
Tested on UK staging :heavy_check_mark:
=> Missing semicolon in nginx config

inventory/host_vars/_example.com/config.yml, inventory/host_vars/prod2.openfoodnetwork.org.au/config.yml, roles/app/templates/application.yml.j2
In https://github.com/openfoodfoundation/openfoodnetwork/pull/3970 I'm changing the way feature toggles are switched on or off. It now uses environment variables instead of a hardcoded hash that was set in an initializer.
This is the second and last part of #444.
=> Add new switch for connect-and-learn feature

roles/deploy/tasks/deploy.yml
The addition of the `rails_safe_fix` gem introduced an error in the deploy playbook. It only affects the first deployment on a fresh server with `RAILS_ENV=production`.
One of the tasks in the deploy playbook is blocked by the gem. This fixes the error by allowing the task to proceed.
=> Fix rails_safe_tasks issue with deploying new production servers

inventory/host_vars/openfoodnetwork.de/config.yml
The German instance is not really used until we get the performance improvements deployed there. Two workers should be good for now. The server has been downscaled to 4 GB.
=> Downscale Germany

roles/deploy/tasks/deploy.yml, roles/deploy/tasks/main.yml, roles/deploy/tasks/rollbacks.yml, tests/deploy/setup.yml, tests/deploy/test.yml, tests/suite.yml
We previously had a bug related to symlinks that meant files were not being backup up correctly in the /rollbacks directory. The change applied to fix it broke the way images are symlinked into the /current directory, but only affected instances that don't use S3, and probably only became apparent after 2 deploys.
I've made some adjustments and added some additional tests to ensure it doesn't happen again and both issues are resolved.
=> Symlink issue

roles/unicorn_user/templates/defaults.j2
This way we can provide different DB credentials for each environment without having to change any config file since now `config/database.yml` reads the env vars.
This allows me to have specific credentials for my LXC setup without having to edit config/database.yml` manually.
More importantly, this helps us remove the line
```
- { src: "postgresql.yml.j2", dest: "{{ config_path }}/database.yml" }
```
from `roles/app/tasks/main.yml` and rely on the app's database.yml only. This will address https://github.com/openfoodfoundation/ofn-install/issues/387
=> Add OFN_DB_USERNAME and OFN_DB_PASSWORD env vars to app user

inventory/host_vars/www.openfoodnetwork.org.uk/config.yml, roles/datadog/tasks/nginx_stats.yml, roles/datadog/tasks/pg_stats.yml, roles/datadog/templates/dd-nginx.j2, roles/datadog/templates/dd-postgres.j2
Separates nginx and postgres logging via datadog so they can be enabled individually.
=> Enable use of nginx or postgres logging separately

playbooks/deploy_with_maintenance.yml, playbooks/v2_deploy.yml, roles/maintenance_mode/tasks/disable.yml, roles/maintenance_mode/tasks/enable.yml, roles/maintenance_mode/tasks/main.yml
Automates the manual steps detailed in https://github.com/openfoodfoundation/ofn-install/wiki/Deployment-of-v2. While human need focus and commit mistakes, computers are fast and
reliable and can also be audited.
Better late than nothing :sweat_smile:
=> Automate the deployment of v2

inventory/host_vars/app.katuma.org/config.yml, inventory/host_vars/www.openfoodfrance.org/config.yml
Closes #495 
This will send the Nginx logs to Datadog where they can be inspected an analyzed.
=> Enable Nginx log monitoring for FR and ES

roles/webserver/templates/unicorn.rb.j2
Closes #498 
Enables Unicorn's `preload_app` option, which should make Unicorn memory usage more efficient.
Tested and working :heavy_check_mark: 
I think we would need to put this on a server with Datadog metrics to properly analyse it.
=> Use `preload_app` option for Unicorn memory improvements

inventory/host_vars/www.openfoodnetwork.org.uk/config.yml, roles/app/templates/application.yml.j2, roles/datadog/tasks/main.yml
Part two of #496 
Depends on: https://github.com/openfoodfoundation/openfoodnetwork/pull/4151
The PR above has to be merged and deployed before using this one.
Adds optional use of Rails APM with Datadog.
Tested on UK Staging (and removed afterwards). :heavy_check_mark:
=> APM in the uk

.travis.yml, inventory/group_vars/all.yml, roles/brotli_nginx/defaults/main.yml, roles/brotli_nginx/tasks/build.yml, roles/brotli_nginx/tasks/fix.yml, roles/brotli_nginx/tasks/main.yml
Closes #504 
- Builds Brotli module from source instead of installing from ppa
- Fixes issues caused by the previous Brotli ppa (US and France)
- Avoids nginx auto-update issues
Tested in Vagrant, French Staging, and Katuma Staging.
=> Build Brotli module from source

inventory/group_vars/all.yml, inventory/host_vars/_example.com/config.yml, inventory/host_vars/app.katuma.org/config.yml, inventory/host_vars/local_travis/config.yml, inventory/host_vars/openfoodireland.eu/config.yml, inventory/host_vars/openfoodnetwork.ca/config.yml, inventory/host_vars/openfoodnetwork.de/config.yml, inventory/host_vars/openfoodnetwork.net/config.yml, inventory/host_vars/prod2.openfoodnetwork.org.au/config.yml, inventory/host_vars/staging.katuma.org/config.yml, inventory/host_vars/staging.openfoodfrance.org/config.yml, inventory/host_vars/staging.openfoodnetwork.org.au/config.yml, inventory/host_vars/staging.openfoodnetwork.org.uk/config.yml, inventory/host_vars/staging2.openfood.com.au/config.yml, inventory/host_vars/staging2.openfoodnetwork.org.uk/config.yml, inventory/host_vars/www.openfoodfrance.org/config.yml, inventory/host_vars/www.openfoodnetwork.be/config.yml, inventory/host_vars/www.openfoodnetwork.in/config.yml, inventory/host_vars/www.openfoodnetwork.org.au/config.yml, inventory/host_vars/www.openfoodnetwork.org.uk/config.yml, inventory/host_vars/www.openfoodnetwork.org.za/config.yml, playbooks/deploy.yml, playbooks/deploy_with_maintenance.yml, playbooks/provision.yml, roles/datadog/tasks/main.yml
Adds a simple `host_id` variable that can be used in Ansible tasks. We currently use `{{ ansible_limit }}` in some places to extract values like `es-prod`, but when using commands with groups like `--limit europe` this will fail.
It's really difficult (and messy) to accurately extract this value from the groups variables when a broader group is used, so we can just define it per-host.
It's really useful in things like Datadog where you want to apply a human-readable tag to metrics being sent from a host, as an identifier that can then be used for filtering.
=> Add `host_id` variable

inventory/host_vars/app.katuma.org/config.yml
This makes it possible to execute queries from Metabase against Katuma's
production DB, as a first towards a global Business Intelligence tool
while allowing Katuma to bill its customers reliably.
This enables us to start collecting the pricing for each of the currently active hubs and producers and start charging them reliably.
Next step will be to use https://github.com/openfoodfoundation/ofn-data data streaming.
=> Enable remote access from Metabase to Katuma's DB

bin/requirements.yml, inventory/group_vars/all.yml, playbooks/provision.yml
Closes #503 and https://github.com/openfoodfoundation/ofn-install/issues/96
Adds central management of logrotate rules.
This should help a bit when investigating issues, and will help clean up bloated and outdated logs. 
We can extend the logrotate rules from this central point any time we need to regularly clean up any kind of files.
=> Rotate Rails and (Datadog) Postgres Query logs

roles/datadog/tasks/main.yml, roles/datadog/tasks/memcached_stats.yml, roles/datadog/templates/dd-memcached.conf.j2
Closes #515 
Adds `memcached` monitoring to instances that use Datadog.
=> Add memcached monitoring to Datadog

Vagrantfile, inventory/group_vars/all.yml, roles/deploy/tasks/deploy.yml
Related to https://github.com/openfoodfoundation/openfoodnetwork/pull/4250
Provisions servers with Ruby `2.1.9`. 
The old Ruby `2.1.5` and associated gems will remain on the servers. We can tidy them up later by setting `rbenv_clean_up: true`.
=> Ruby bump: ofn-install edition

inventory/hosts
ofn-secrets does not include its secrets.yml yet so commands would fail for the ZA server.
=> Remove ZA from all-prod group

inventory/host_vars/openfoodnetwork.net/config.yml
Part 2 of: https://github.com/openfoodfoundation/ofn-install/issues/513
Allows Zapier access to Postgres and sets Postgres to listen for external connections (for the Zapier IP only).
=> Allow Zapier user access to Postgres for USA

inventory/host_vars/staging.openfoodnetwork.org.uk/config.yml, roles/datadog/tasks/main.yml
We need to be able to test changes in monitoring quickly and reliably without having to risk production. This will incur an extra cost but it'll save money in dev hours testing things in the long run.
=> Enable Datadog's APM in UK staging

inventory/group_vars/all.yml, roles/common/templates/memcached.conf.j2, roles/unicorn_user/templates/defaults.j2
- Related to #4256
In bug [#4256](https://github.com/openfoodfoundation/openfoodnetwork/issues/4256) 447 products were taking 1MB of space. We need to change max size of cache values to 4MB so we can handle at least 2k products.
This problem will need to be addressed differently when the product list is paginated. We will probably be able to revert this change as each page will never take more than 1MB.
This PR takes care of configuring the memcached server to use 4 MB. The memcached client library, which in this case is `dalli`, also needs to be configured to allow storing values up to this size - this is done in https://github.com/openfoodfoundation/openfoodnetwork/pull/4356.
This PR is best to be provisioned and tested with this PR's branch deployed: …
=> Increase max size of cache entries so products cache can be larger than the default 1MB

inventory/group_vars/ca.yml
Canada's server is using en. This makes it use en_CA.
We may want to run the following SQL on the server after deploy so that all users will immeditely see this language:
update spree_users set locale = 'en_CA' where locale = 'en';
=> Make Canada's server to use en_CA

roles/deploy/tasks/deploy.yml
Closes #467 
Does not install `development` and `test` dependencies in production.
Tested in Vagrant. :heavy_check_mark:
=> Only install required gems in production

roles/shared_handlers/handlers/main.yml
Closes https://github.com/openfoodfoundation/openfoodnetwork/issues/4328 
Cleaning assets before precompiling assets make translations always being updated, even if JS code is not updated.
Maybe there's some i18n-js config we could change to achieve this but I have not managed to find it.
I tested this PR and the problem is fixed because a new JS bundle is always generated.
Maybe another dev can verify the process again in staging. Or we can just deploy 2.5.2 again to FR live and see if the problem is fixed, it's harmless.
Changelog Category: Fixed
Translations stored in the browser (Javascript) are now always updated even if no code changes on the javascript side.
=> Make assets precompile tasks always clean assets before

inventory/group_vars/all.yml
- Adjusts replication privileges to use a separate user, with tighter permissions
- Defines `Debezium` version in a central place for easier dependency upgrades
=> Update replication user settings

inventory/group_vars/de.yml
As requested by Kirsten.
This needs the new language en_DE to be added to the main ofn repo first.
=> Change en to en_DE on the german instance

inventory/group_vars/all.yml
Part 2 of: https://github.com/openfoodfoundation/openfoodnetwork/issues/2891
Provisions Ruby `2.2.10` ready for use with PR: https://github.com/openfoodfoundation/openfoodnetwork/pull/4301
=> Install Ruby 2.2.10

inventory/host_vars/www.openfoodfrance.org/config.yml
Closes https://github.com/openfoodfoundation/openfoodnetwork/issues/4439
Increases timeouts on French prod from 120 to 240. 
This is due to `Orders and Fulfilment` reports timing out. These should be fixed soon :crossed_fingers: so this is a temporary measure.
=> Increase timeouts for French production

inventory/group_vars/fr.yml
As requested by instance manager.
en_FR.yml is already merged through https://github.com/openfoodfoundation/openfoodnetwork/pull/4440
=> Add en_FR as available locale on french instance

inventory/host_vars/www.openfoodnetwork.org.uk/config.yml
Increase Uk timeout to make reports run.
This has been provisioned to uk and the reports now work after 7mins.
Fixes https://github.com/openfoodfoundation/openfoodnetwork/issues/4521
=> Increase uk timeout to 720secs

inventory/host_vars/staging.katuma.org/config.yml
I thought this was disabled long ago but Datadog was still monitoring
the infrastructure (that the minimum service they provide when no APM is
enabled). It turns out only this flag stops the stats collection daemon.
This should lower the monthly bill a little bit.
=> Disable Datadog in Katuma staging

inventory/group_vars/all.yml, playbooks/provision.yml
Twinned with https://github.com/openfoodfoundation/openfoodnetwork/pull/4518
- Installs Ruby `2.3.7`
- Ensures previous version (`2.2.10`) is installed, for smoother testing process in CI builds
=> Provision Ruby 2.3.7

inventory/host_vars/_example.com/secrets.example.yml, roles/app/templates/application.yml.j2
Twinned with https://github.com/openfoodfoundation/openfoodnetwork/pull/4653
Allows setting an alternate region for S3 backups bucket.
=> Allow setting an alternate region for S3 backups bucket

inventory/host_vars/www.openfoodfrance.org/config.yml, inventory/host_vars/www.openfoodnetwork.org.uk/config.yml
Closes #544 
Moves APM from UK to France in preparation for the datastreaming trial.
=> Move Datadog APM from UK to France

inventory/host_vars/www.openfoodfrance.org/config.yml
This should resolve the certificate issue when accessing https://openfoodfrance.org. Right now, only www.openfoodfrance.org is supported.
Through curl:
```shell
$ curl https://openfoodfrance.org
curl: (51) SSL: no alternative certificate subject name matches target host name 'openfoodfrance.org'
```
From the browser, I get `NET::ERR_CERT_COMMON_NAME_INVALID`.
=> Add non-www support for certbot in fr-prod

inventory/hosts
We want to avoid deploying to it by mistake until the reliability issues are not fixed yet. We experienced weird issues that we managed to fix when deploying v2.7.4 and finally decided to roll it back to v2.7.3.
It's very likely that any new deploy will screw things up. Better to avoid it.
=> Remove AU production server from the prod list

inventory/host_vars/staging.openfoodfrance.org/config.yml, inventory/host_vars/staging.openfoodnetwork.org.uk/config.yml
Last bill was $183.16 covering Datadog January 2020: 3 Commited Hosts
@ $54.00, 3 On-Demand Hosts @ $54.00, 2 On-Demand APM Hosts @ $72.00,
1.239 On-Demand Log Events (millions) @ $3.16.
This change should save us $90 every month, not a whole lot but we're
not checking staging's metrics. We can enable it temporally when
changing Datadog's config and disable it back again.
=> Disable Datadog in stagings to save money

inventory/host_vars/prod2.openfoodnetwork.org.au/config.yml
A report is using more than 4GB of memory to be generated. This should
increase the likelyhood that it's successful without crashing anything.
It's a difficult balance because too much swap can just slow down the
server until it's not reacting any more. -> Trial and error.
=> Increase swap space for au-prod

inventory/group_vars/all.yml
We've settled on Ruby 2.3.7 now, we don't need to spend an extra 10 minutes in each CI run (or new deployment) building Ruby 2.2.10 as well :rocket:
=> Don't build Ruby twice in every build

inventory/group_vars/all.yml
The "text/html" option is included by default and shouldn't be in the list: https://nginx.org/en/docs/http/ngx_http_gzip_module.html#gzip_types
=> Fix gzip_types declaration

bin/requirements.yml
Related to #571 
Bumps the `certbot_nginx` role. 
This update includes a patch I submitted that allows certificates to be regenerated when the configs have changed.
This means if we update the certificate configs for a server, for example with France where it previously only had `www.openfoodfrance.org` in the list of domains but we have added the bare domain `openfoodfrance.org` to the list, we can use the following Ansible command to recreate the certificate with the updated configuration (the default behaviour is to ignore it if a certificate is already present):
`ansible-playbook playbooks/provision.yml --limit fr-prod --tags certbot -e "certbot_force_update=true"`
=> Bump certbot_nginx role

playbooks/deploy.yml
Now if you don't type the command correctly when deploying a release on a production server, you'll see this prompt _before_ the playbook runs, instead of realising after the playbook has finished that you've accidentally deployed `master` to production because of a typo... :see_no_evil: : 
:muscle: :muscle: :muscle:
=> Avoid mistakenly deploying master to production due to minor typos

roles/deploy/tasks/deploy.yml, roles/deploy/tasks/precompile.yml
Closes https://github.com/openfoodfoundation/openfoodnetwork/issues/4819
Precompiling assets looks a bit different in Rails 4, it's one task instead of two, and the syntax is changed. 
This PR runs slightly different precompile tasks during deployments, based on a quick check in the Gemfile to see if Rails 3 is being used.
=> Precompiling in Rails 4

.lexi/container.yml, .lexi/network.yml, .lexi/users.yml, inventory/group_vars/lexi.yml, inventory/host_vars/local_lexi/config.yml, inventory/hosts
Adds configs for using `lexi` for testing ofn-install. Uses Linux Containers via LXD.
See: https://github.com/libre-ops/lexi for installation and usage (it's really good...)
=> Add configs for using lexi (dev testing with LXD)

inventory/group_vars/es.yml
A new hub that trades with French customers asked Katuma for these languages.
=> Enable French and English in Katuma

inventory/host_vars/app.katuma.org/config.yml, inventory/host_vars/openfoodnetwork.org.au/config.yml, inventory/host_vars/staging.katuma.org/config.yml, inventory/host_vars/staging.openfoodfrance.org/config.yml, inventory/host_vars/staging.openfoodnetwork.org.uk/config.yml, inventory/host_vars/www.openfoodnetwork.org.uk/config.yml
Closes https://github.com/openfoodfoundation/openfoodnetwork/issues/5085
Since UK was the first instance to enable this service, and disable it later on, its settings are still in `ofn-secrets` but AU needs openfoodfoundation/ofn-secrets#29.
I removed old disabling commands from staging servers, that I can confirm, don't have the DD agent running. I manually expired their API keys to be extra sure. 
I also disabled it for Katuma production since we don't check its monitoring and AU needs it much more than Katuma.
=> Enable apm for UK and AU

roles/app/templates/application.yml.j2
Twinned with: https://github.com/openfoodfoundation/openfoodnetwork/pull/5113
Allows configuration of a separate Bugsnag API key for javascript errors per-instance.
=> Enable use of separate API key for javascript Bugsnag calls

inventory/group_vars/all.yml, inventory/host_vars/openfoodnetwork.org.au/config.yml, roles/webserver/tasks/main.yml, roles/webserver/templates/unicorn.service.j2, roles/webserver/templates/unicorn_environment.j2
- Enables `unicorn-worker-killer` on all staging and production servers.
- Adds a missing lograte entry for exponential unicorn log
- Improves how ENV vars passed to unicorn service
=> Kill Unicorns

playbooks/postgres_tuning.yml
This tunes a few memory-related Postgres settings that we hope will make use of the available RAM. Still, the server is not leveraging those 16Gb RAM.
I based my decision on https://www.citusdata.com/blog/2018/06/12/configuring-work-mem-on-postgres/. It's not the first time I read `work_mem` should be much higher than the default. I remember reading time ago that it should be 16Mb. We need to check and see :man_shrugging: 
This has already been applied to the UK.
=> Increase Postgres work_mem

inventory/group_vars/lexi.yml
I must have missed this when committing previously. 
Tweaks the nginx configs for lexi (LXD) containers so they work without letsencrypt certificates.
=> Fix nginx config for lexi

.python-version, .travis.yml, README.md, playbooks/db_integrations.yml, requirements.txt
This brings in the [requirements file](https://pip.readthedocs.io/en/1.1/requirements.html) Python uses to manage dependencies with Pip, Python's package manager, to migrate to Ansible 2.9.6.
Then, as we do with `bundle install`, when dependencies are changed, you need to run `pip install -r requirements.txt`.
It makes use of [Pyenv](https://github.com/pyenv/pyenv) (an Rbenv's clone to manage Python versions) and its [pyenv-virtualenv](https://github.com/pyenv/pyenv-virtualenv) plugin.
This relies on a [virtualenv](https://virtualenv.pypa.io/en/latest/) set up in your environment called `ofn-install`. It's the same idea as RVM's gemsets and it's the way Python isolates dependencies.
This is what we've been using in all our Python projects at Coopdevs (which is almost all of them).
=> Make ofn-install run on Ansible 2.9.6

roles/webserver/templates/unicorn.rb.j2
This setting means unicorn doesn't get hit if the queued connection has been cancelled before it gets to unicorn, i.e. if a user hits the refresh button 10 times in 1 second, don't process each of those requests because most of them are already technically been terminated on the client side.
Details in the original commit notes: https://github.com/defunkt/unicorn/commit/5c700fc2cf398848ddcf71a2aa3f0f2a6563e87b
The notes mention it worked really well on Black Friday, so this should help with our "Black Monday" situations on UK Prod :trollface:
=> Check unicorn client connections

playbooks/deploy.yml
I wanted to correlate the changes in performance with a particular release but we are missing that data in Datadog.
=> Tell Datadog which app version was deployed

playbooks/db_transfer.yml, roles/db_transfer/defaults/main.yml, roles/db_transfer/tasks/main.yml
Closes: #575 
Adds a playbook for migrating data from one server to another, transferring the database dump directly between the two using SSH agent forwarding. 
This should greatly reduce the downtime involved in migrating a server.
=> Add playbook for database migration with SSH forwarding

playbooks/postgres_tuning.yml
I noticed today that the changes we did to UK's settings for PostgreSQL to take up more RAM weren't loaded by the server. A query against the `pg_settings` view returned (among other settings):
```
name            | shared_buffers
setting         | 16384 # Equivalent to 128MB
unit            | 8kB
category        | Resource Usage / Memory
short_desc      | Sets the number of shared memory buffers used by the server.
extra_desc      |
context         | postmaster
vartype         | integer
source          | configuration file
min_val         | 16
max_val         | 1073741823
enumvals        |
boot_val        | 1024
reset_val       | 16384
sourcefile      |
sourceline      |
pending_restart | t
```
So yes, manually restarting the server switched that `pending_restart` to false and the …
=> Forcefully restart PostgreSQL to reload config

.travis.yml
We better run our CI on a Python supported version. Not sure which sort of edge cases we might run into with the latest Ansible but an unmaintained Python version.
~This also requires upgrading to Ubuntu 18.04 but AU has been running it in production for quite some time so we do know it's safe.~
=> Upgrade CI to Python 3

ansible.cfg, playbooks/deploy.yml, playbooks/provision.yml
Closes #588 
Related to: #575 
Adds some enhancements to Ansible itself and to some playbooks:
**Enable Ansible's "Pipelining" feature**
Reduces the number of active connections and the amount of data transferred by Ansible when it runs tasks. This should reduce latency issues during trans-atlantic playbook execution
**Increase Ansible forking maximum**
Maximum number of forking processes Ansible will create locally when running playbooks against multiple servers. The default is 5. We regularly run playbooks on 8 servers at once (all-prod), so this should help speed things up.
**Use "free" strategy in provision and deploy playbooks**
When running playbooks on multiple servers, Ansible will normally wait until every server has completed a task before moving to the next one. Using the …
=> Ansible tuning

inventory/host_vars/openfoodnetwork.ca/config.yml
Part of #605 
Adds Zapier configs for `ca-prod`.
After the secrets changes in https://github.com/openfoodfoundation/ofn-secrets/pull/35 are merged, and the changes here are merged, we need to:
- run the `db_integrations.yml` playbook on `ca-prod`
- provision `ca-prod`
=> Add zapier configs to ca-prod

inventory/host_vars/migration.katuma.org/config.yml, inventory/hosts
Related to https://github.com/openfoodfoundation/openfoodnetwork/issues/5418
I dropped the following from the existing config:
* `swapfile_size`: We migrate to have more RAM (8GB) thus, no need for swap
anymore
* `enable_nginx_logging`: Datadog is not enabled so this config is set
but not used.
* `disable_datadog`: The new server doesn't have it so a `true` won't
take in effect here.
I added the extra `certbot_domains` entry as documented in
https://github.com/openfoodfoundation/ofn-install/wiki/Migrating-a-Production-Server.
As for the entry `alpha.katuma.org`, the old subdomain we redirect to `app.katuma.org`, we need to decide whether we still maintain it or not. It's likely that we'll take the chance to drop it.
=> Add config settings for Katuma's server migration

playbooks/transfer_assets.yml, roles/db_transfer/tasks/main.yml, roles/migrate_assets/defaults/main.yml, roles/migrate_assets/tasks/rsync_assets.yml
Related to https://github.com/openfoodfoundation/openfoodnetwork/issues/5418
Adds a playbook for transferring all custom instance assets directly between two servers using rsync and SSH forwarding.
Uses the same transfer method as the (relatively new) `db_transfer` playbook.
Katuma uses local storage for images, and we have to transfer ~1.3GB of assets between the two servers for the migration. So: lets do it in one fast transfer of 1.3GB using the high bandwidth of two web servers, instead of two slow transfers of 1.3GB download and then 1.3GB upload (with crappy bandwidth both ways)... 
:rocket:
=> Rsync asset transfer

playbooks/transfer_assets.yml
This fixes the following failure we had at the first attempt at migrating the assets
```
failed: [app.katuma.org -> 116.203.60.113] (item=images) => {                                                                                                                         [141/1202]
"ansible_loop_var": "migrate_dir",                                                                                                                                                          
"changed": false,                                                                                                                                                                           
"cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh=/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o …
```
=> Use user with the necessary permissions

roles/common/tasks/main.yml
Related to https://github.com/openfoodfoundation/openfoodnetwork/issues/5418
Without it, in the brand new Katuma's server we suddenly got this error when printing invoices:
```
2020-05-20T16:35:17+0200: [Worker(delayed_job host:katuma-production pid:17737)] Job BulkInvoiceService#start_pdf_job_without_delay (id=695942) FAILED (3 prior attempts) with RuntimeError: Failed to execute:
["/home/openfoodnetwork/.gem/ruby/2.3.0/bin/wkhtmltopdf", "-q", "--encoding", "UTF-8", "file:////tmp/wicked_pdf20200520-17737-vogzkt.html", "/tmp/wicked_pdf_generated_file20200520-17737-e9yk2z.pdf"]
Error: PDF could not be generated!
Command Error: /home/openfoodnetwork/.gem/ruby/2.3.0/gems/wkhtmltopdf-binary-0.12.5/bin/wkhtmltopdf_ubuntu_18.04_amd64: error while loading shared libraries: libXrender.so.1: …
```
=> Install lib required by wkhtmltopdf

roles/deploy/tasks/deploy.yml
Removing the current path for the last time apparently messes with assets a bit in this case. Subsequent deployments are fine, it's just the initial one that needs a restart.
=> Restart unicorn when deploying with the old method for the last time

playbooks/setup.yml
Purges any potential outdated `nginx` packages that come pre-installed in the server (during setup).
Outdated nginx packages can sometimes cause issues and refuse to be updated. This bug is difficult to reproduce and seems to vary depending on the image used. Only affects new server installs, but we've encountered this several times and purging `nginx` before provisioning fixes it.
Green build should be enough. If the task succeeds in the CI build, there's nothing more to check.
=> Fix outdated nginx package issue

roles/deploy/handlers/main.yml
Closes https://github.com/openfoodfoundation/openfoodnetwork/issues/5535
This avoids creating duplicate entries in the crontab in the future and automatically clears up any duplicate entries in existing crontabs.
=> Add explicit path for use with whenever gem

roles/webserver/templates/unicorn.rb.j2
Possibly fixes: #633 
Ensure the new unicorn process finds the new Gemfile when changing builds.
See: https://stackoverflow.com/a/16555086
=> Unicorn reload Gemfile fix

roles/webserver/templates/unicorn_environment.j2
Related to issue #633 and PR #636
One last try with this assets issue. The previous error (https://github.com/openfoodfoundation/ofn-install/pull/636#issuecomment-638812136) has changed to one relating to bundler:
```
I, [2020-06-04T15:58:50.876913 #1624]  INFO -- : executing ["/home/openfoodnetwork/.gem/ruby/2.3.0/bin/unicorn", "-D", "-c", "/home/openfoodnetwork/apps/openfoodnetwork/shared/config/unicorn.rb", "-E", "staging", {15=>#<Kgio::UNIXServer:fd 15>}] (in /home/openfoodnetwork/apps/openfoodnetwork/releases-old/2020-06-04-155407)
/home/openfoodnetwork/.rbenv/versions/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
from /home/openfoodnetwork/.rbenv/versions/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_requi …
```
=> Ensure bundler has an explicit Gemfile path when used via systemd

roles/db_integrations/tasks/main.yml
Related to https://github.com/openfoodfoundation/openfoodnetwork/issues/5418
I just ran `playbooks/db_integrations.yml` but I had to manually restart PostgreSQL for the changes to take effect. It was a surprise because Geerlingguy's PostgreSQL role already deals with that in the task that changes the config (Configure host based authentication (if entries are
configured).). This task though, reported a OK:
```
TASK [geerlingguy.postgresql : Configure host based authentication (if
entries are configured).]
***********************************************************************************************
Thursday 28 May 2020  08:13:53 +0200 (0:00:03.535)       0:00:27.106
**********
[DEPRECATION WARNING]: evaluating u'postgresql_hba_entries' as a bare
variable, this behaviour will go away and …
```
=> Restart PostgreSQL when user is added

inventory/group_vars/all.yml
Recommended setting; enables us to have an accurate and straightforward way of checking the client IP addresses (in production) in Rails, with: `request.headers['X-Real-IP']`. 
Currently we get really confusing results in Bugsnag for example, where the IP always appears to be the same for each request, because it's actually the IP of the server not the client.
=> Set 'X-Real-IP' header when reverse-proxying from nginx to Rails app.

inventory/host_vars/app.katuma.org/config.yml, inventory/host_vars/openfoodnetwork.org.au/config.yml
I decreased the swap size for Australia because we don't need that much swap and we need more disk space.
When I last provisioned Katuma, I also encountered an error trying to remove Datadog even though it's gone already. So I took that one out as well.
=> Updated host vars for AU and Katuma

inventory/host_vars/_example.com/config.yml, inventory/host_vars/_example.com/secrets.example.yml, inventory/host_vars/app.katuma.org/config.yml, inventory/host_vars/openfoodnetwork.de/config.yml, inventory/host_vars/openfoodnetwork.org.au/config.yml, inventory/host_vars/staging.openfoodfrance.org/config.yml, inventory/host_vars/www.openfoodfrance.org/config.yml, inventory/host_vars/www.openfoodnetwork.org.uk/config.yml, roles/app/defaults/main.yml, roles/app/templates/application.yml.j2
To remove the page admin/image_settings/edit from OFN ([this PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/5729)), we need to add an alternative way to change and track these settings.
Some are already in ofn-secrets:
s3_access_key
s3_secret
s3_images_bucket (which is converted to s3_bucket)
To keep consistency, in this PR, we add the 2 remaining S3 entries to ofn-secrets (to the example file) where the other ones are. It looks like this:
s3_headers: "{\"Cache-Control":"max-age=31557600\"}"
s3_protocol: "https"
In this PR we also set defaults for all image settings and copy custom settings from all servers to each server config.yml file.
I provisioned staging FR with this PR and I do get the images settings in application.yml as well as the custom ATTACHEMENT_PATH :+1: …
=> Add image settings to ofn-install

bin/requirements.yml, inventory/group_vars/all.yml, playbooks/provision.yml, roles/deploy/tasks/deploy.yml, roles/yarn/defaults/main.yml, roles/yarn/tasks/main.yml
This installs node and npm using https://github.com/geerlingguy/ansible-role-nodejs
and then uses npm to install yarn.
I tried a few other things but this was the only way to control the exact version of yarn we install. I didnt manage to control exact version of node though. So, with this we have node 14.x and yarn 1.22.4
node --version
v14.2.0
yarn --version
1.22.4
How to test:
- provisioning a server should leave node and yarn available on the command line
- deploy a version should create the node_modules folder - this folder will be empty for now because production mode will not deploy devDependencies. I tested this without the production flag and the modules like karma were deployed :+1:
=> Add "install yarn" to the provision playbook and "yarn install" to the deploy playbook

inventory/group_vars/us.yml
This fixes issue 6003 in the [openfoodnetwork repo](https://github.com/openfoodfoundation/openfoodnetwork/issues/6003) from Laurie. 
It should be pretty straightforward; I don't know what the process for testing something like this would look like, if we should deploy it to a staging server first to make sure nothing bombs out (what if I'd mistyped en_US as en_USA for example and the en_USA.yml file doesn't exist, for example?)
The other consideration is whether transifex has been keeping en_US.yml up to date; I did `diff en.yml en_US.yml` and took a quick glance through and nothing jumped out as wrong, mostly swapping "organisation" for "organization" and things like that.
=> use US-specific locale for translating strings

inventory/host_vars/staging.openfoodnetwork.org.au/config.yml, inventory/host_vars/staging2.openfood.com.au/config.yml, inventory/host_vars/staging2.openfoodnetwork.org.uk/config.yml, inventory/host_vars/www.openfoodnetwork.org.au/config.yml
Testing openfoodfoundation/openfoodnetwork#5729 the images were broken and I noticed that the attachment path had changed. I checked all hosts managed by the global community and added the path were it was missing and different to the default.
This should be merged before openfoodfoundation/openfoodnetwork#5729 so that we can test with the right config on any staging server.
Outdated configs were removed to reduce the amount of files which may need adjustments.
=> Add image settings to hosts missing them

inventory/host_vars/www.coopcircuits.fr/config.yml, inventory/hosts
This configuration will allow the new domain for FR_prod, coopcircuits.fr.
This PR should be merged on Wednesday, 23rd of September evening, just before the migration process.
=> Add new configuration for new FR_prod domain

inventory/host_vars/app.katuma.org/config.yml, inventory/host_vars/www.coopcircuits.fr/config.yml, roles/app/templates/application.yml.j2
We had some post-deployment fun this morning with broken image paths on `es-prod` and `fr-prod` due to two separate issues.
The updated values here are what I've already applied in production on both servers to fix them.
I've also removed a value here as we don't need it. See commit messages for details.
=> Fix broken image paths

inventory/group_vars/all.yml
I noticed some minor errors related to this whilst debugging something else... in most configurations the pg_log file doesn't exist so we should tell logrotate to ignore it in that case.
=> Minor tweak: ignore missing log files for pg queries

inventory/group_vars/all.yml
Adds HTTP method whitelisting to our nginx configs :muscle:
Any request from a browser or as part of an API call will reasonably declare one of the standard HTTP methods. We get a large volume of requests with no valid HTTP method declared, and they generally look pretty nasty. Examples of the kind of thing that gets sent with no valid HTTP method (and usually no user-agent header either):
For anyone that likes trawling log files, here's what all of our nginx traffic from the last 7 days for UK and France looks like when you filter out the requests with valid HTTP methods: [nasty logs](https://app.datadoghq.com/logs?cols=%40response_time%2C%40http.status_code%2C%40http.url_details.path%2C%40http.method%2C%40http.useragent&from_ts=1602279149870&index=&live=true&messageDisplay=inline&query=- …
=> Whitelist HTTP methods

playbooks/deploy.yml
The original check here was not running on non-core production servers. This small update to the logic will be more helpful for instances that are not managed by the core team.
=> Update "deploying to master" check

roles/unicorn_user/templates/defaults.j2
Allows setting `mail_auth_type`. This is a standard mail config setting, but was previously not configurable via ofn-install and was just set to a hard-coded default.
Needed for Sendgrid API authentication. Tested and working in UK Staging :heavy_check_mark: 
Twinned with: https://github.com/openfoodfoundation/openfoodnetwork/issues/6365
To use the Sendgrid API method (after these two PRs are merged) the new settings are:
```yaml
mail_auth_type: "plain"
smtp_username: "apikey"
smtp_password: "<api-key-from-sengrid-account>"
```
=> Allow MAIL_AUTH_TYPE to be set

roles/datadog/templates/status.conf.j2
This status page is only accessed internally for stats collection. It shouldn't be accessible externally. The original config here meant that nginx was binding on 0.0.0.0 port 81, which is not necessary. External access to the port was producing a 403/Forbidden response (which is not too bad), but it shouldn't leave that port open at all.
=> Improve nginx stub_status config

inventory/host_vars/openfoodnetwork.org.au/config.yml, inventory/host_vars/staging.coopcircuits.fr/config.yml, inventory/host_vars/staging.openfoodnetwork.org.au/config.yml, inventory/host_vars/www.coopcircuits.fr/config.yml, inventory/host_vars/www.openfoodnetwork.be/config.yml, inventory/host_vars/www.openfoodnetwork.org.uk/config.yml
This PR updates the config for all servers using S3 to store images. The url is now the S3 URL including the bucket name and the region. See original issue https://github.com/openfoodfoundation/openfoodnetwork/issues/4177 and the main PR https://github.com/openfoodfoundation/openfoodnetwork/pull/6258
=> Add new attachment URLs for all servers using S3

inventory/host_vars/www.coopcircuits.fr/config.yml
Fixing a quick typo in the configs so the poor sucker** that deploys to production next Tuesday doesn't have any nasty surprises with all images suddenly being broken on `fr-prod`.
See https://github.com/openfoodfoundation/ofn-install/pull/667/files for reference.
\** it's me this week :sweat_smile:
=> Fix typo in fr-prod attachment_url

roles/deploy/tasks/deploy.yml, roles/deploy/tasks/precompile.yml
We extracted it into a separate file when upgrading to Rails 4 as asset precompilation changed from two to one rake task, adding a conditional to support both Rails versions now that it's back to a plain simple ansible task there's no need for the indirection.
=> Inline task from dumb precompile.yml

inventory/host_vars/openfoodnetwork.ca/config.yml
Closes https://github.com/openfoodfoundation/ofn-install/issues/679. It requires https://github.com/openfoodfoundation/ofn-secrets/pull/49 first.
=> Enable Datadog's APM for CA production

inventory/host_vars/openfoodnetwork.net/config.yml
Closes #687. It requires https://github.com/openfoodfoundation/ofn-secrets/pull/50 first.
=> Enable Datadog's APM for US production

inventory/group_vars/all.yml
This was done for 2.3.7 here: https://github.com/openfoodfoundation/ofn-install/pull/549
This is needed for https://github.com/openfoodfoundation/openfoodnetwork/pull/6441
=> Add ruby 2.4.4 to list of ruby versions so we can gracefully upgrade servers

roles/webserver/tasks/main.yml, roles/webserver/templates/delayed_job.service.j2, roles/webserver/templates/unicorn.service.j2
Fixes #680.
These changes ensure that unicorn and delayed job are booting at the right time without errors. I also noticed a few other bits to improve, including a security concern.
I tested this on au-staging and it seems to work well.
=> Systemd service updates: boot order, timeouts, permissions

inventory/group_vars/all.yml, inventory/group_vars/au.yml, inventory/group_vars/ca.yml, inventory/group_vars/es.yml, inventory/group_vars/fr.yml
I wanted to remove myself from having access to servers.
Then I decided to update a few more users to keep the current global sysadmin group current. It's just a proposal. We can keep as is if anyone disagrees with the changes.
=> Update security groups to reflect current reality

playbooks/remove_ssh_keys.yml
Closes https://github.com/openfoodfoundation/openfoodnetwork/issues/6607
Adds a simple playbook for removing SSH keys.
Tested and working :heavy_check_mark:
=> Add playbook for removing SSH keys

inventory/group_vars/all.yml
This enables Datadog's HTTP request queue tracking. See https://docs.datadoghq.com/tracing/setup_overview/setup/ruby/#http-request-queuing.
=> Add custom HTTP header to track request queuing

roles/deploy/tasks/deploy.yml
Related to: https://github.com/openfoodfoundation/openfoodnetwork/issues/5643
The result of this symlink was that precompiled assets were shared between builds in a way that they shouldn't have been, and other issues with assets (especially in Rails 4) were obfuscated; old versions of non-digest assets which technically should *not* be available, actually are available **in some cases, on some servers, in a flaky way**. :see_no_evil:
:warning: We shouldn't merge this until the other assets cleanup PRs in the main repo are all tested and merged.
Additional note: manually deploying master to a staging server with this PR makes it really obvious which things need to be fixed. Any assets that still need to be fixed should be clearly missing after deploying then clearing browser cache / using …
=> Don't symlink assets directory into the build

inventory/host_vars/app.katuma.org/config.yml, inventory/host_vars/staging.katuma.org/config.yml
Enrico freaked out when he saw 10 test emails in Coopdevs' inbox. These and other admin-related better go to Katuma's inbox.
=> Use Katuma's admin email instead of Coopdevs'

inventory/host_vars/openfoodnetwork.ca/config.yml
The new CA server has around 5.5Gb of free RAM so there's no point in having any swap, which when used, slows things down a few orders of magnitude.
This will hopefully mitigate https://github.com/openfoodfoundation/openfoodnetwork/issues/6802 but won't solve it.
=> Don't use swap in CA production

inventory/host_vars/migration.openfoodnetwork.net/config.yml, inventory/hosts
This might not even need to be merged? More just an FYI to anyone in the future or who might be working on the migration. Because I ran the `provision.yml` script more than five times I got rate limited by LetsEncrypt so I had to change the subdomain.
=> Rename subdomain for USA migration

roles/migrate_assets/defaults/main.yml
Updates the `transfer_assets` playbook to bring it in line with asset changes made since the last server migration.
- `/assets` path is removed. We excluded this from being persisted between deployments, it should only contain precompiled assets which will be generated during deployments, so it doesn't need to be transferred when migrating servers.
- `/files` path is added. This directory now contains uploaded T&C PDFs, and we need to transfer them when migrating a server.
Tested and working :heavy_check_mark:
=> Asset transfer update

inventory/host_vars/migration.openfoodnetwork.net/config.yml
Quick update to the temporary configs for the US server migration...
These changes are live now on the `us-migrate` server (certificates recreated)
=> US migration configs

playbooks/provision.yml
Closes #702
Apparently the package has changed, and the old one is no longer present, so it can't be installed correctly on new servers. It's fine on exiting server that have already installed it.
=> Update certbot package name

roles/deploy/tasks/deploy.yml
This happens after the backup of the previous release has been made and before the migration step. Ensures the old data is cleared regularly and that larger migrations will be more efficient.
=> Clear transient data during deployment

inventory/host_vars/www.coopcircuits.fr/config.yml, inventory/host_vars/www.openfoodnetwork.org.uk/config.yml
The output being written to `application.yml` was:
```
BETA_TESTERS: a,l,l
```
due to the way the list items are split in the template file.
=> Fix beta_testers configs

inventory/hosts
FR_staging server is back in shape, https://staging.coopcircuits.fr, I have created this PR to update the new IP.
fyi, I tried to deploy it with ansible recipes under Ubuntu 20.04 but it fails due to Ubuntu changing 'python-apt' package which is required into 'geerlingguy.security'. Then I put it to Ubuntu 18.04 where the only issue I faced was related to GD library dependency for Nginx which was fixed installing manually 'libgd-dev' package.
=> Use new FR_staging ip in hosts file

inventory/host_vars/_example.com/secrets.example.yml, roles/app/templates/application.yml.j2
If instances want a SSO integration with Discourse or to use [alternate geocoder services](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/config/initializers/geocoder.rb) we could add these environment variables to servers. Although maybe it's ok for those variables to be just added via `custom_application_env_vars`, feel free to close this if so.
=> Add environment variables for Discourse SSO and alternate geocoder services to servers if present

inventory/group_vars/all.yml
Closes #735 
Pulls the defaults out of the rbenv role into `all.yml` and switches the rbenv-installer configuration to point at the newly renamed branch.
=> Fix rbenv-installer

roles/common/handlers/main.yml, roles/common/tasks/main.yml, roles/common/tasks/redis.yml, roles/common/templates/redis.conf.j2, roles/deploy/tasks/check_redis.yml, roles/deploy/tasks/deploy.yml, roles/webserver/templates/delayed_job.service.j2, roles/webserver/templates/unicorn.rb.j2, roles/webserver/templates/unicorn.service.j2
Part of https://github.com/openfoodfoundation/openfoodnetwork/issues/7541
- Installs and configures Redis
- Does _not_ remove Memcached (we can do that later, and we need to maintain some backwards-compatibility during the transition period until all servers are updated) :ok_hand: 
- Adds a failsafe check in `deploy.yml` to stop deployment if Redis is in the Gemfile but has not been installed yet (for instances not managed by the core team, so we don't break anything in production) :heart:
=> Provision Redis

roles/app/templates/application.yml.j2, roles/unicorn_user/templates/defaults.j2
Sets up: https://github.com/openfoodfoundation/openfoodnetwork/pull/7673
Updates the way mail-related configs are passed to the app. Previously we were setting them in the environment of the unicorn user, but now we pass them to the app itself.
When testing this I also noticed there are some cases where unicorn is restarted where the ENV vars for the unicorn user are not actually passed to Rails, possibly due to the service being restarted as root (sudo)? :warning: (that's fixed now)
=> Pass configs needed for mail to the app

roles/compatibility/tasks/main.yml
This outdated SSL package is no longer required to build Ruby on modern systems since Ruby 2.4.x
:tada:
Also frees up the rebenv role's `rbenv_extra_depends` variable to be used for more useful things, like installing `jemalloc`...
=> Remove libssl1.0-dev dependency

inventory/group_vars/all.yml, inventory/host_vars/local_travis/config.yml
The Travis build environment is really flaky, and it apparently doesn't like `jemalloc`.
This avoids using it in Travis when testing our playbooks.
=> Don't use jemalloc in Travis

roles/deploy/handlers/main.yml
The Travis build environment doesn't like running Sidekiq via a service, so we can skip it here. We don't really test Sidekiq or jobs processing in any of our playbook tests here anyway, so it's not a huge loss. This should get the ofn-install build back to green (it's currently red).
Side note: this is the third annoying issue that's come up recently relating to the Travis build environment, it would be good to try switching to Github CI for running the ofn-install build at some point...
=> Don't start Sidekiq in Travis

roles/deploy/handlers/main.yml
Another step in phasing out `delayed_job`. Ignores errors if the service isn't found.
=> Ignore delayed_job errors if the service has been removed

roles/deploy/tasks/deploy.yml
WIP
Apparently this flag can cause issues and is not recommended.
=> Remove --production flag from yarn install step

roles/app/templates/env.j2
This will take the following settings if defined in secrets and include them as ENV variables:
```
openid_app_id
openid_app_secret
openid_redirect_uri
```
These settings will be used in https://github.com/openfoodfoundation/openfoodnetwork/pull/7880 to configure an instance's Open ID Connect integration. This is being added as part of the work on the DFC API.
Specifically they'll be used in the devise initializer:
https://github.com/openfoodfoundation/openfoodnetwork/blob/35869e1be812d03385b565fe3c99c3f47b109601/config/initializers/devise.rb#L150-L152
=> Add Open ID ENV variables if defined

.github/workflows/build.yml
This should avoid downloading and compiling the Ruby source code in every build, cutting the build time dramatically.
=> Cache the rbenv directory in the ofn-install build

roles/deploy/tasks/deploy.yml
We currently install dev and test gems when deploying to staging. This means we currently end up with Rails running through Spring servers in staging, which is a really bad idea...
=> Exclude development and test gems in staging

roles/semaphore_deployment/templates/deploy.j2
Closes https://github.com/openfoodfoundation/openfoodnetwork/issues/7986
When deploying to staging via Semaphore, specific versions of master (including releases) will use the exact commit, but pull requests will use the latest version of the branch merged with master. This means we'll get accurate release versions staged, but we'll also include recent changes when testing PRs that haven't been rebased recently.
=> Update Semaphore deployment script

inventory/group_vars/all.yml, roles/webserver/templates/puma.service.j2
- Removes a temporary nginx config used for transitioning from unicorn to puma
- Loosens the restart timers in the puma systemd service so they're not as aggressive. This potentially led to some deployment issues, but I didn't manage to replicate the problem directly. The new settings are in line with the old ones we used with unicorn.
=> Puma taming

roles/app/templates/env.j2
This value is not a secret, we put it directly into the Devise configuration here, https://github.com/openfoodfoundation/openfoodnetwork/pull/7880/files#diff-cb6e8126296dbc007e7625eee863de5c3213ed949b9999ea3418775f65826531R158
=> Remove oidc redirect_uri from env var check

inventory/group_vars/all.yml
Adds some TLS hardening and ensures ciphers blacklisted under the HTTPS2 spec don't get mistakenly used when connections are upgraded from HTTPS1 on the fly.
Should resolve some recent reports on certain Mac OSX / Safari versions resulting in `ERR_HTTP2_INADEQUATE_TRANSPORT_SECURITY` errors with HTTPS.
Also boosts our TLS analysis rating on www.ssllabs.com from a **B** to an **A+** :ok_hand:
=> Add updated TLS cipher suite configuration

inventory/group_vars/all.yml
Each log file has to be rotated explicitly now. That makes sure that we apply rotation rules suited for each file.
But I would also be happy to go another path and log sidekiq via systemd. I guess that we would just need to remove the redirection from the service:
https://github.com/openfoodfoundation/ofn-install/blob/59888d0078b4a4a28b4983ec54355e6238d3d1e7/roles/sidekiq/templates/sidekiq.service.j2#L14-L16
**WIP:** the first commit belongs to another PR but I wanted to avoid conflicts.
=> Avoid truncation of sidekiq log

inventory/group_vars/all.yml
Australian production used over 90% of its disk. I provisioned this already. :heavy_check_mark: 
Closes #806.
=> Rotate puma.log to save disk space

roles/common/tasks/main.yml
Uploaded product images are transformed into different sizes but we were missing the webp tools to transform .webp images. This is now added.
If you want to reproduce the bug:
- Choose a staging server other then au-staging because I installed webp there already.
- Go to /admin/products.
- Upload a webp file.
Testing this pull request:
- Have SSH access to the staging server and ofn-install set up with Ansible.
- Check out this pull request and run:
- `ansible-playbook -l fr-staging -t packages playbooks/provision.yml` or uk-staging.
- Then go to /admin/products.
- Upload a webp file.
```
ansible-playbook -l all-staging -t packages playbooks/provision.yml
ansible-playbook -l all-prod -t packages playbooks/provision.yml
```
=> Support webp images

bin/requirements.yml, inventory/group_vars/all.yml, playbooks/provision.yml, playbooks/setup.yml, roles/common/tasks/main.yml, roles/compatibility/tasks/main.yml
I did my best to create atomic commits with messages full of details.
This should close issue https://github.com/openfoodfoundation/ofn-install/issues/811
I have developed using Vagrant by changing the the image to focal64. Then I ran:
`vagrant destroy -f && vagrant up && ansible-playbook --limit vagrant playbooks/setup.yml && ansible-playbook --limit vagrant playbooks/provision.yml && ansible-playbook --limit vagrant playbooks/deploy.yml`
After I got all these commands to run without errors I check in the browser if http://localhost:8080 loaded OFN homepage without errors.
With everything working in 20.04 I got back the Vagrantfile to xenial and bionic, repeating the test detailed above, in order to check if my changes had no unwanted side effects in them. All looked good in my tests. …
=> Add support to Ubuntu 20.04

roles/datadog/tasks/main.yml
Ubuntu 16 is not supported any more and `apt update` was failing.
=> Remove old apt source which caused failures

inventory/group_vars/all.yml, roles/app_user/tasks/main.yml, roles/ssh_keys/tasks/main.yml
* Fixes #829
We are not deleting the keys from the repository yet because we need to know they key in order to delete it from the server.
Whenever we add a key, we should run:
ansible-playbook playbooks/provision.yml -l all-prod -t ssh_keys,app_user
=> Remove old SSH admin keys

bin/requirements.yml, inventory/group_vars/all.yml, roles/dbserver/tasks/main.yml
It was failing due to an outdated repository. And it was used for Metabase which is currently broken and that approach has been abandoned.
=> Remove wal2json from provisioning

bin/requirements.yml
Many fixes including around APT management which has been a problem.
=> Bump datadog from 3.1.0 to 4.16.0

bin/requirements.yml, inventory/group_vars/all.yml, playbooks/db_integrations.yml
The db_integrations playbook was broken. I guess that the internal workings of the postgresql role changed and it didn't expect a subtask to be included on its own. I'm now including the whole role as in the provisioning playbook to make it work again and reduce maintenance. It will be a little bit slower though.
=> Update postgres role and config for db integration

roles/yarn/tasks/main.yml
unblock the installation of yarn on the CI: an issue exist about this on the NPM module : ansible/ansible#29240 (comment) The workaround is to use enviroment to define the PATH in ansible's yaml
=> Unblock the installation of yarn on the CI (#1)

inventory/group_vars/fr.yml
This is related to the peformance issue we faced in France.
https://github.com/openfoodfoundation/openfoodnetwork/issues/9859
Increasing the workers and threads manually seems to give us better performance. Note that we have 8 workers on Nginx side. The idea was that Nginx requests were flooding Puma requests pool.
Oct 23, 5:10 pm – Oct 23, 11:19 pm
Oct 30, 5:10 pm – Oct 30, 11:19 pm
Even if it is not easy to compare as there is a bit less traffic on the second date, it seems to have a positive impact to have increase these workers and threads.
=> Increase Puma workers and threads for FR config

.github/workflows/build.yml, inventory/group_vars/all.yml, requirements.txt
Actually, do not close  #838
* **Yarn** latest version
* **Node** no change
* **GH Actions** latest version each
* **Python** latest version
* Jinja2: lock to older version of Jinja2 (From memory, due to both Ansible 2.7 and our code)
Not sure how to test it actually. I guess this is a question for @mkllnk and @heroinedor ;)
=> Upgrade to latest `yarn` version + upgrade all GH actions

inventory/group_vars/all.yml
Closes #851
Probably the best way is to provision a staging server (not the FR one), which is well configured + deploy https://github.com/openfoodfoundation/openfoodnetwork/pull/9804 on that server and check that on `/admin/orders` page you don't have any websocket errors
=> Add websockets connection to `/cable`

roles/webserver/templates/puma.rb.j2
This gem is 6 years old and makes puma 6 not start: remove it
Seems unnecessary when using ruby 2.7
https://github.com/ko1/nakayoshi_fork/issues/5
Unblocks:
* https://github.com/openfoodfoundation/openfoodnetwork/pull/10217
=> Remove nakayoshi_fork gem from puma config

roles/db_integrations/tasks/main.yml, roles/db_integrations/templates/cert-renewal-hook.sh.j2
When database integrations accessed our database over the internet, Postgresql was using a self-signed certificate which makes us vulnerable to man-in-the-middle attacks. But we can easily use our Letsencrypt certificate for more secure connections.
* Enabling #822 in a secure way.
Postgresql doesn't have access to the certificate files though and we have to tell certbot to copy the files for postgresql.
I used au-staging to test this and it is provisioned already. So use another staging server like uk-staging to run the db_integrations playbook:
```
ansible-playbook --vault-password-file ../.ansible-vault-password --limit uk-staging --extra-vars @../ofn-secrets/uk-staging/secrets.yml playbooks/db_integrations.yml
```
Make sure that the OFN app still works. Connect n8n to the database …
=> Use valid TLS certificate for db integrations

roles/datadog/tasks/pg_stats.yml, roles/dbserver/tasks/main.yml
It's only used for Datadog but the Rails application is tracking extensions in its schema.rb file. Rails tries to create the extension itself if it doesn't exist and the db user is not allowed to create exensions at the moment. This seemed to be the easiest way but we could also give the db user the CREATE privilege instead.
Provision fr-staging and then try to deploy OFN master. It should succeed now. The other two staging servers have the extension already.
Follow up from:
- https://github.com/openfoodfoundation/openfoodnetwork/pull/10278
=> Create stats extension on all servers

inventory/group_vars/all.yml, inventory/host_vars/app.katuma.org/config.yml, inventory/host_vars/coopcircuits.fr/config.yml, inventory/host_vars/openfoodnetwork.be/config.yml, inventory/host_vars/openfoodnetwork.ca/config.yml, inventory/host_vars/openfoodnetwork.de/config.yml, inventory/host_vars/openfoodnetwork.hu/config.yml, inventory/host_vars/openfoodnetwork.ie/config.yml, inventory/host_vars/openfoodnetwork.net/config.yml, inventory/host_vars/openfoodnetwork.org.au/config.yml, inventory/host_vars/openfoodnetwork.org.nz/config.yml, inventory/host_vars/openfoodnetwork.org.uk/config.yml, inventory/host_vars/staging.coopcircuits.fr/config.yml, inventory/host_vars/staging.openfoodnetwork.org.au/config.yml, inventory/host_vars/staging.openfoodnetwork.org.uk/config.yml
Preparation for:
* https://github.com/openfoodfoundation/openfoodnetwork/issues/9161
Our Metabase server has been working with replicated databases. But our replication setup breaks regularly and we lost the knowledge how it works.
To simplify the setup, we are going to connect Metabase directly to the live database (with a statement timeout).
This pull request allows connecting to postgresql. We will still need to add the user with a secret password managed in ofn-secrets.
=> Allow Metabase to connect to managed databases

roles/deploy/handlers/main.yml, roles/deploy/tasks/deploy.yml
And a bit more cleaning.
We disabled DelayedJob a long time ago. We can consider all servers updated or an older version needs to be used.
=> Remove transition code from DelayedJob

README.md, playbooks/provision.yml
* Fixes #861
This was faulty: it would copy the latest files, but not load the values into memory, until next time you run ansible. Therefore you're always one step behind, and could copy old config onto a server (this has happened).
I tried to fix it with ansible's `refresh_inventory` command, but frustratingly can't get it to work:
* closes https://github.com/openfoodfoundation/ofn-install/pull/867
So I suggest you have to manually execute `fetch_secrets.yml` before provisioning.
After merging I'll also update the wiki:
1. https://github.com/openfoodfoundation/ofn-install/wiki/Provisioning#using-ofn-secrets
2. https://github.com/openfoodfoundation/ofn-install/wiki/Tips-for-core-sysadmins#setup-1
=> Remove auto fetch of ofn secrets

roles/common/tasks/main.yml
The libvips42 library enables use of ruby-vips for faster image processing.
=> Add libvips42 to base apt packages

inventory/host_vars/openfoodnetwork.net/config.yml
This should be reset after the cloning has been made more efficient:
* https://github.com/openfoodfoundation/openfoodnetwork/pull/10832
=> Allow more time for cloning order cycles

inventory/host_vars/staging.openfoodnetwork.org.au/config.yml
- #797
Konrad has access to the other two staging servers, but not this one yet.
Requires provisioning:
ansible-playbook playbooks/fetch_secrets.yml # always be sure to have updated secrets first
ansible-playbook playbooks/provision.yml --limit au-staging -t app_user
=> Add Konrad's key to au-staging

roles/deploy/tasks/deploy.yml
Preparing for future Ruby upgrades.
* Unblocks https://github.com/openfoodfoundation/openfoodnetwork/pull/10888
There's more work to do. We currently install a specific Ruby version during provisioning which we don't need any more. But this pull request took me long enough to take a break here and continue another time.
=> Install ruby on deploy

roles/datadog/tasks/main.yml
* Prepares https://github.com/openfoodfoundation/ofn-install/issues/885
There's quite a bit to do to remove all our custom Datadog configurations but in the meantime it's very simple to just deactivate the Datadog agent services. fr-prod was the only host using it and I applied this change already. Hopefully Datadog will stop charging us now.
=> Disabled datadog agents

inventory/host_vars/_example.com/secrets.example.yml, roles/app/templates/env.j2
Related to #[10997](https://github.com/openfoodfoundation/openfoodnetwork/pull/10997)
Update secretes template and add environment variables needed to enable new relic : 
* NEW_RELIC_AGENT_ENABLED
* NEW_RELIC_APP_NAME
* NEW_RELIC_LICENSE_KEY
Once #[11256](https://github.com/openfoodfoundation/openfoodnetwork/pull/11256) is merged New relic can be turned on by setting the env variables.
=> Add new relic env variable

.lexi/container.yml
Bumps default Ubuntu version in the configs for testing Ansible branches locally with LXD.
=> Update Ubuntu version in LXD local testing setup

bin/requirements.yml, playbooks/provision.yml
Matt changed the underscore to a dash and downloading the role failed.
```
- downloading role 'multi_redis', owned by libre_ops
- downloading role from https://github.com/libre_ops/multi_redis/archive/1.0.1.tar.gz
Error: ]: failed to download the file: HTTP Error 404: Not Found
Warning: : - libre_ops.multi_redis was NOT installed successfully.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```
https://github.com/openfoodfoundation/ofn-install/actions/runs/6374617784/job/17299450784
=> Update name of multi_redis repository

playbooks/provision.yml, roles/config/README.md, roles/config/handlers/main.yml, roles/config/tasks/main.yml
To avoid hard drive filling up.
Dunno if it was a problem before, but it was easy to copy from another project.
Tested on au-staging:
```
~/projects/ofn-install $ ansible-playbook playbooks/provision.yml --tag=config -l au-staging
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
PLAY [provision] *******************************************************************************************************
Thursday 05 October 2023  14:02:39 +1100 (0:00:00.122)       0:00:00.122 ******
TASK [Gathering Facts] *************************************************************************************************
ok: [staging.openfoodnetwork.org.au]
Thursday 05 October 2023  14:02:41 +1100 (0:00:01.888)       0:00:02.010 ******
TASK [config : Set journal log …
```
=> Set lower limit for journald logs

.github/workflows/build.yml, bin/requirements.yml, roles/dbserver/tasks/postgresql.yml
The build takes best part of an hour but it does run the whole suite and makes sure that the app is running on a fresh container.
=> Fix CI build on Github Actions

inventory/hosts
Ansible was complaining:
```
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
```
Dashes are not allowed in group names like au-prod.
=> Rename host group names for valid Ansible names

bin/setup-lxc
This was my initial setup. It can be tweaked, of course.
=> Add convenience script to set up LXC

inventory/group_vars/all.yml
JB left the organisation and I removed his SSH key from all servers already:
```
ansible-playbook playbooks/remove_ssh_keys.yml --limit all_prod,all_staging -e "{'remove_users_sysadmin':[jb]}"
```
This change makes sure that we don't add it again.
=> Retire JB's ssh access

inventory/hosts
To ensure it gets deployed each week.
I considered creating an 'asia' group, but there's no need to group when there's only one so far.
=> Add in_prod to list of globally managed servers

inventory/group_vars/all.yml
**What? why?**
- Related to https://github.com/openfoodfoundation/openfoodnetwork/issues/12020
- ActionCable is unable to modify the query string due to the difference in domains. In the `products_reflex.rb#current_url` the `request.original_url` gets set to `https://rails` instead of the configured domain because no `Host` header is sent
- Send relevant headers in the action cable location block
**What should we test**
- Currently no tests written yet
- Staging was manually tested by @mkllnk and worked https://github.com/openfoodfoundation/ofn-install/pull/920#discussion_r1520582714
- We should test prod to confirm fix addresses issue, hence [#12020](https://github.com/openfoodfoundation/openfoodnetwork/issues/12020) should remain open until that fact
**References** …
=> Pass in configured domain to ActionCable - related to #12020

inventory/host_vars/staging.openfoodnetwork.org.au/config.yml, inventory/host_vars/staging.openfoodnetwork.org.uk/config.yml
This was to avoid multiple Englishes appearing
* Reported on https://github.com/openfoodfoundation/openfoodnetwork/issues/11513
There still seems to be some other issue, but I think this is still necessary.
This has already been provisioned on au_staging and uk_staging.
=> Update locale settings

inventory/group_vars/all.yml, inventory/host_vars/_example.com/config.yml, inventory/host_vars/app.katuma.org/config.yml, inventory/host_vars/coopcircuits.fr/config.yml, inventory/host_vars/csicsoka.org/config.yml, inventory/host_vars/openfoodnetwork.be/config.yml, inventory/host_vars/openfoodnetwork.ca/config.yml, inventory/host_vars/openfoodnetwork.de/config.yml, inventory/host_vars/openfoodnetwork.ie/config.yml, inventory/host_vars/openfoodnetwork.net/config.yml, inventory/host_vars/openfoodnetwork.org.au/config.yml, inventory/host_vars/openfoodnetwork.org.nz/config.yml, inventory/host_vars/openfoodnetwork.org.uk/config.yml, inventory/host_vars/staging.coopcircuits.fr/config.yml, inventory/host_vars/staging.openfoodnetwork.org.au/config.yml, inventory/host_vars/staging.openfoodnetwork.org.uk/config.yml
Fix #924
Update `ph_hba.conf` to allow the new N8N server to connect to postgres database
I added both IPv4 and IPv6 entry, I am not sure if it's strictly necessary but it doesn't hurt to cover everything
=> Add configuration to allow N8N to connect to the database

roles/app/tasks/main.yml, roles/shared_handlers/handlers/main.yml
Ensure relevant services are restarted, after updating Rails or Postgres environment variables. Normally they would be restarted when the full provision playbook is executed anyway, but my vision is to be able to perform individual actions quicker. 
My vision: to update app config in a minute with`--tags=app`, instead of waiting ages for every single action to run. 
Probably this could have been separated into two separate tasks (one for Rails and one for Postgres). But it didn't seem worth spending more time on. Especially because additional tasks make ansible even slower...
I'm not sure why it failed on CI.
Update: I thought it was time to act on this one, so found a way to avoid the sidekiq error. Hmm, perhaps it was never started on initial setup? Then we should probably fix that.. …
=> Restart after config changes

inventory/host_vars/csicsoka.org/config.yml, inventory/hosts
https://openfoodnetwork.slack.com/archives/C0DNLAZC7/p1721824249711239
=> Change domain csicsoka.org to openfood.hu

inventory/host_vars/openfoodnetwork.org.uk/config.yml, inventory/host_vars/staging.openfoodnetwork.org.uk/config.yml, roles/app/templates/env.j2
UK prod is getting a rather high number of Rack Timeout errors : https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/664378ec33e1080008ba685a?filters[error.status]=open&filters[event.since]=30d . Most likely due to long running queries.
As explained in the docs : https://github.com/zombocom/rack-timeout/blob/master/doc/settings.md#term-on-timeout it can cause the application to enter a in a corrupt state, and can cause database connection to not be released back in the db connection pool. This is most likely what has been happening on uk prod, we are seeing a high number of `ActiveRecord::ConnectionTimeoutError` see https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/664b458a96db3b0007ce304a?filters[error.status]=open&filters[event.since]=30d
To mitigate the issue we can …
=> Add RACK_TIMEOUT_TERM_ON_TIMEOUT for uk-prod

inventory/host_vars/coopcircuits.fr/config.yml
Part of https://github.com/openfoodfoundation/openfoodnetwork/issues/12761
same as `uk-prod` #932, adding RACK_TIMEOUT_TERM_ON_TIMEOUT to mitigate issue with the db connection pool.
=> Add RACK_TIMEOUT_TERM_ON_TIMEOUT for fr-prod

inventory/host_vars/_example.com/secrets.example.yml, inventory/host_vars/staging.coopcircuits.fr/config.yml, inventory/host_vars/staging.openfoodnetwork.org.au/config.yml, inventory/host_vars/staging.openfoodnetwork.org.uk/config.yml, roles/app/templates/env.j2
**⚠️ When working on this use the Clockify code: Citi Food Vouchers: #1A. https://github.com/openfoodfoundation/openfoodnetwork/issues/11922 Citi OFN Voucher - VINE Integration ⚠️**
Related to : https://github.com/openfoodfoundation/openfoodnetwork/pull/12886
Update env template and secret example to include activerecord encryption configuration and VINE_API_URL config.
=> [Citi OFN Voucher] Add Activerecord encryption configuration and VINE api config

.github/workflows/build.yml, .python-version, README.md
I needed to re-create my Python environment. So I decided to try the latest patch release of the current version and it seems to work. :tada: 
It just reached end of life last month... but updating is another project. Except, Github Actions doesn't support 3.8.20... okay, let's try the next version up.
After updating to this version, you need to install the new version and create a new environment:
```
pyenv install 3.9.20
pyenv virtualenv 3.9.20 ofn-install-3.9.20
cd your/path/to/ofn-install
pip install -r requirements.txt
```
=> Bump Python from 3.8.2 to 3.9.20

.github/workflows/build.yml, .python-version, README.md, bin/pyenv-install
Testing another increment of the minor version.
=> Bump Python from 3.9.20 to 3.10.15

inventory/host_vars/staging.coopcircuits.fr/config.yml
- https://openfoodnetwork.slack.com/archives/CEBMTRCNS/p1726451615941249
Last month the memory usage hit 100% and interrupted testing. It  hasn't happened again, but I think it's worth having as a backup. Then the server will just slow down instead of crashing, which should still be enough of a canary to warn that something's going wrong. There's plenty of free disk space.
This hasn't been executed yet. 
Once approved I'll provision, using tag `swapfile`.
=> Add swapfile to fr_staging

.github/workflows/build.yml, README.md, requirements.txt
If we want to keep using Ansible, we need to update to a modern version, supporting current versions of Python. This is just a first step.
Related:
* #157 
* #863 
It may be necessary to remove the old version of Ansible entirely. This will do the trick:
```
pyenv virtualenv-delete ofn-install-3.10.15
./bin/pyenv-install
```
=> Bump ansible from 2.9.20 to 2.10.7

inventory/hosts
openfoodnetwork.ie has been upgraded to Ubuntu 20 now by following the instructions at https://github.com/openfoodfoundation/ofn-install/wiki/Migrating-a-Production-Server which were a great help. 
I noticed that the `pull_assets.yml` and `push_assets.yml` playbooks don't include the `storage` directory [here](https://github.com/openfoodfoundation/ofn-install/blob/master/roles/migrate_assets/defaults/main.yml). If an instance is configured to use `local` ActiveStorage this can be an issue, because I had to manually copy over the `storage` directory to the new server,  although most instances probably don't use `local`.
Let me know if you need any more details.
=> Use IP of new Ubuntu 20 server for IE

roles/remote_deployment/templates/deploy.j2
This issue was caused because I took the shortcut to provision all three servers at once:
```
ansible-playbook playbooks/setup_remote_deployment.yml -l all_staging
```
The playbook assumed that the `limit` param only refers to the current server, and pastes it into the deploy script. So I've updated it to specify only a reference to itself.
=> Fix remote deployment script

inventory/group_vars/all.yml
I was going to write an issue for this, so I could move on and avoid spending too much time on it. But I ended up just doing it..
Regex tested here so far, with a handful of examples I pulled out of Bugsnag (not an exhaustive analysis of logs by any means): https://regex101.com/r/lffH5m/1
We could probably block a lot more, but I reckon cutting out php will make a huge dent.
Credit: this was copied and adapted from fairfood-install.
This could be tested on a staging env:
* .php URLs are blocked with a basic 404 error. Not triggered in bugsnag
* able to browse the website normally. 
* Even if a shop has ".php" in the name, it should still work
If success, we can contribute this update back to fairfood-install.
=> Block requests for .php

.github/ISSUE_TEMPLATE/server-migration.md, roles/default_user/tasks/main.yml
Is it ok not to have `netdev` group?
=> Upgrade updates

inventory/group_vars/all.yml, inventory/host_vars/_example.com/config.yml, inventory/host_vars/app.katuma.org/config.yml, inventory/host_vars/coopcircuits.fr/config.yml, inventory/host_vars/openfood.hu/config.yml, inventory/host_vars/openfoodnetwork.be/config.yml, inventory/host_vars/openfoodnetwork.ca/config.yml, inventory/host_vars/openfoodnetwork.de/config.yml, inventory/host_vars/openfoodnetwork.ie/config.yml, inventory/host_vars/openfoodnetwork.net/config.yml, inventory/host_vars/openfoodnetwork.org.au/config.yml, inventory/host_vars/openfoodnetwork.org.nz/config.yml, inventory/host_vars/openfoodnetwork.org.uk/config.yml, inventory/host_vars/staging.coopcircuits.fr/config.yml, inventory/host_vars/staging.openfoodnetwork.org.au/config.yml, inventory/host_vars/staging.openfoodnetwork.org.uk/config.yml
Remove database setting to allow connection from old n8n server
=> Clean up n8n database connection setting

.github/ISSUE_TEMPLATE/server-migration.md, inventory/group_vars/all.yml, inventory/host_vars/_example.com/config.yml, inventory/host_vars/app.katuma.org/config.yml, inventory/host_vars/coopcircuits.fr/config.yml, inventory/host_vars/openfood.hu/config.yml, inventory/host_vars/openfoodnetwork.be/config.yml, inventory/host_vars/openfoodnetwork.ca/config.yml, inventory/host_vars/openfoodnetwork.de/config.yml, inventory/host_vars/openfoodnetwork.ie/config.yml, inventory/host_vars/openfoodnetwork.net/config.yml, inventory/host_vars/openfoodnetwork.org.au/config.yml, inventory/host_vars/openfoodnetwork.org.nz/config.yml, inventory/host_vars/openfoodnetwork.org.uk/config.yml, inventory/host_vars/staging.coopcircuits.fr/config.yml, inventory/host_vars/staging.openfoodnetwork.org.au/config.yml, inventory/host_vars/staging.openfoodnetwork.org.uk/config.yml
Update database configuration to allow connection from the new metabase server.
=> Update database configuration

.github/ISSUE_TEMPLATE/server-migration.md, README.md
Some more updates to the upgrade checklist and readme.
I'd like to update the process further and simplify it.. but haven't got time for that.
=> Upgrade checklist updates

.python-version, requirements.txt
After version 2.10 the ansible-core package continues with 2.11 but the `ansible` community package jumps to version 3.0.0. This doesn't upgrade ansible-core which stays on 2.10.
Tests:
=> Bump Ansible from 2.10 to 3.0

roles/node/defaults/main.yaml
The HEAD branch was renamed. Even after updating the name in Ansible, it still failed on not wanting to override a tag. The workaround is to delete the plugin remotely:
```
rm ~/.nodenv/plugins/node-build/ -rf
```
I don't think it's worth integrating into Ansible. It would be better to switch to a bash script installing node.
=> Update node-build branch from master to main

inventory/group_vars/all.yml, inventory/host_vars/_example.com/config.yml, inventory/host_vars/app.katuma.org/config.yml, inventory/host_vars/coopcircuits.fr/config.yml, inventory/host_vars/openfood.hu/config.yml, inventory/host_vars/openfoodnetwork.be/config.yml, inventory/host_vars/openfoodnetwork.ca/config.yml, inventory/host_vars/openfoodnetwork.de/config.yml, inventory/host_vars/openfoodnetwork.ie/config.yml, inventory/host_vars/openfoodnetwork.net/config.yml, inventory/host_vars/openfoodnetwork.org.au/config.yml, inventory/host_vars/openfoodnetwork.org.nz/config.yml, inventory/host_vars/openfoodnetwork.org.uk/config.yml, inventory/host_vars/staging.coopcircuits.fr/config.yml, inventory/host_vars/staging.openfoodnetwork.org.au/config.yml, inventory/host_vars/staging.openfoodnetwork.org.uk/config.yml
Now that data.openfoodnetwork.org.uk is retired, remove database access. 
I also clean up `au_prod` to be in line with the current production configuration.
=> Remove db access for the old metabase server

playbooks/setup.yml
- Closes #765
This was only executed for Ubuntu older than Ubuntu 20 but all new servers do have Ubuntu 20. We also don't require old Python anymore.
=> Remove old python setup

bin/requirements.yml, inventory/group_vars/all.yml, playbooks/provision.yml, roles/app/tasks/main.yml, roles/common/tasks/main.yml
Now we don't have to manage the ruby version in two places. The bash script in the app is also faster than Ansible. Follow up from:
* https://github.com/openfoodfoundation/openfoodnetwork/pull/13034
=> Skip installing ruby, the app does it

roles/node/tasks/main.yml
- Fixes #968
because node-build keeps updating a tag ref, causing error:
```
Failed to download remote objects and refs:  From https://github.com/nodenv/node-build
43a77880..41c93786  main       -> origin/main
43a77880..41c93786  master     -> origin/master
! [rejected]          v5         -> v5  (would clobber existing tag)
* [new tag]           v5.3.23    -> v5.3.23
```
Now, it should just work when provisioning next.
=> Force fetch nodenv plugins

Vagrantfile
I got this error before:
```
The IP address configured for the host-only network is not within the
allowed ranges. Please update the address used to be within the allowed
ranges and run the command again.
Address: 192.168.50.4
Ranges: 192.168.56.0/21
Valid ranges can be modified in the /etc/vbox/networks.conf file. For
more information including valid format see:
https://www.virtualbox.org/manual/ch06.html#network_hostonly
```
Any objections?
=> Adjust Vagrant IP address to allowed Debian range

playbooks/setup.yml
This reverts commit a872e875d4367adba0bb9dc627a10db303f1d67c.
I misread the conditional chain and thought that the original code was only installing python for old Ubuntu versions. But it was just choosing the right python version depending on the Ubuntu version. We can now assume Python 3 and simplify the check.
=> Re-introduce python installation

playbooks/provision.yml, roles/common/handlers/main.yml, roles/enable_redis/tasks/main.yml
While looking at setting monitoring for all redis instances, I noticed a some of our prod instances don't have the default redis instances. That means we can't update the ActionCable configuration to use said instance as proposed here https://github.com/openfoodfoundation/openfoodnetwork/pull/13072
According to the [documentation](https://redis.io/docs/latest/operate/oss_and_stack/install/install-redis/install-redis-on-linux/) redis should be enable/start automatically but it appears to not always be the case.
This PR add a new role to make sure the default instance of redis is enable and running when provisioning a server.
=> Enable default redis instance

.github/workflows/build.yml, bin/setup-lxc, inventory/hosts, playbooks/setup.yml, roles/config/tasks/main.yml
We were running provisioning and deploy through a local connection on the Github runner itself. But when we upgrade to Ubuntu 22 and higher, that fails because of the permissions within the Github Actions container. So I decided to use a lightweight container which I've been using in development as well.
Now we are independent of the Github images and we could even run the tests against multiple Ubuntu versions in parallel.
The LXC setup took a little bit longer but not much:
* Old local setup: 17m
* LXC setup: 19m
=> Run tests on CI with LXC container 

.github/workflows/build.yml, Vagrantfile, bin/requirements.yml, bin/setup-lxc, inventory/group_vars/all.yml, inventory/hosts, playbooks/provision.yml, playbooks/setup.yml, roles/app_user/tasks/main.yml, roles/common/tasks/main.yml, roles/config/tasks/main.yml
Relates to:
* #157
Includes and depends on:
* #989
The brotli compilation failed on newer Ubuntu versions. I chose the easy path for now to deactivate brotli for newer Ubuntu since it's only relevant for a few servers and only when we actually replace servers again.
From Ubuntu 24 onwards, brotli can be installed via apt. That may require replacing the used nginx role which isn't maintained any more anyway. That's a different task though.
=> Add support for Ubuntu 22 and Ubuntu 24

bin/pyenv-install
If an old version of python is active, the install got skipped (at least, on Mac). 
This script now checks if the specified virtual env is active or not.
=> Update pyenv-setup script

roles/db_integrations/tasks/main.yml
Our n8n server connects to Postgresql databases directly. The connection is encrypted and needs valid certificates. We re-use our Letsencrypt certificates that we get for nginx anyway and copy them for Postgresql.
Now, David T reported that the global dashboard hasn't been updated since December 2024. Testing one of the workflows, n8n reported that the certificated for au_prod was expired. The renewal hook had not been run. Newer versions of certbot have more specific paths for renewal hooks and our hook was still in the old path. I updated that now.
I didn't bother removing the old file. It would be temporary code and the file is not doing any harm. In fact, if one of the servers still uses an old version of certbot, deleting the old file may break database integrations.
I tested this on …
=> Update path for certbot renewal hooks

roles/db_integrations/tasks/main.yml
Now that the hook is in the right place, it gets called automatically.
Follow up from:
* #995
I noticed that I hadn't updated the path in this line but it can actually be removed. I'm already provisioning this version:
* https://github.com/openfoodfoundation/ofn-install/pull/995#issuecomment-2749723209
=> Remove superfluous hook reference

roles/common/tasks/main.yml
* Unblocks https://github.com/openfoodfoundation/openfoodnetwork/pull/13232
All servers have been updated already.
=> Install libyaml-dev to build psych gem for Rails 7.1
